import type { LucideIcon } from "lucide-react";
import {
  Terminal,
  Crown,
  FolderTree,
  Code2,
  Sliders,
  Bot,
  Webhook,
  Shield,
  ShieldCheck,
  Sparkles,
  TrendingUp,
  Boxes,
  Users,
  Settings,
  Zap,
  Landmark,
  Workflow,
  Target,
  Radio,
  Eye,
  ScrollText,
  Flame,
  Activity,
  Layers,
  Cpu,
  Wrench,
  KeyRound,
  LayoutDashboard,
  Server,
  FileCode,
  Gauge,
  Database,
  Lock,
} from "lucide-react";

export type PanelColorType = "solid" | "pearl" | "gradient";

export type PanelColor =
  // Sólidas & Neon
  | "rose"
  | "amber"
  | "cyan"
  | "emerald"
  | "violet"
  | "indigo"
  | "blue"
  | "orange"
  | "ruby"
  | "fuchsia"
  | "purple"
  | "lime"
  | "teal"
  | "yellow"
  | "slate"
  // Cores Peroladas (Lustre iridescente / madrepérola)
  | "pearl-white"
  | "pearl-black"
  | "pearl-rose"
  | "pearl-gold"
  | "pearl-cyan"
  | "pearl-jade"
  | "pearl-lavender"
  // Degradês (Gradients dinâmicos)
  | "gradient-cyber"
  | "gradient-sunset"
  | "gradient-aurora"
  | "gradient-galaxy"
  | "gradient-fire"
  | "gradient-hyper"
  | "gradient-gold"
  | "gradient-matrix"
  | "gradient-amethyst";

export interface PanelColorStyle {
  key: PanelColor;
  label: string;
  description: string;
  hex: string;
  previewGradient?: string;
  colorType: PanelColorType;
  textClass: string;
  iconClass: string;
  textMutedClass: string;
  bgSubtleClass: string;
  bgSolidClass: string;
  borderClass: string;
  borderHoverClass: string;
  borderSubtleClass: string;
  activeItemClass: string;
  badgeClass: string;
  ringClass: string;
  glowClass: string;
  itemHoverClass?: string;
  itemIconHoverClass?: string;
}

export const PANEL_COLOR_STYLES: Record<PanelColor, PanelColorStyle> = {
  // ─── CORES SÓLIDAS & NEON ───
  rose: {
    key: "rose",
    label: "Rosa Neon / Magenta",
    description: "Visual de terminal cibernético e comandos avançados",
    hex: "#f43f5e",
    colorType: "solid",
    textClass: "text-rose-400",
    iconClass: "text-rose-400",
    textMutedClass: "text-rose-400/70",
    bgSubtleClass: "bg-rose-500/10",
    bgSolidClass: "bg-rose-600 text-white",
    borderClass: "border-rose-500/40",
    borderHoverClass: "hover:border-rose-500/60",
    borderSubtleClass: "border-rose-500/20",
    activeItemClass: "font-black text-rose-400 bg-rose-500/15 border border-rose-500/40 shadow-xs shadow-rose-500/10 rounded-lg",
    badgeClass: "bg-rose-500/20 text-rose-300 border-rose-500/40",
    ringClass: "ring-rose-500/40",
    glowClass: "shadow-rose-500/20",
    itemHoverClass: "hover:text-rose-400 hover:bg-rose-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-rose-400",
  },
  amber: {
    key: "amber",
    label: "Âmbar / Dourado Real",
    description: "Visual executivo nobre de diretoria e liderança",
    hex: "#f59e0b",
    colorType: "solid",
    textClass: "text-amber-400",
    iconClass: "text-amber-400",
    textMutedClass: "text-amber-400/70",
    bgSubtleClass: "bg-amber-500/10",
    bgSolidClass: "bg-gradient-to-r from-amber-500 to-yellow-500 text-black",
    borderClass: "border-amber-500/40",
    borderHoverClass: "hover:border-amber-500/60",
    borderSubtleClass: "border-amber-500/20",
    activeItemClass: "font-black text-amber-300 bg-amber-500/15 border border-amber-500/40 shadow-xs shadow-amber-500/10 rounded-lg",
    badgeClass: "bg-amber-500/20 text-amber-300 border-amber-500/40",
    ringClass: "ring-amber-500/40",
    glowClass: "shadow-amber-500/20",
    itemHoverClass: "hover:text-amber-400 hover:bg-amber-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-amber-400",
  },
  cyan: {
    key: "cyan",
    label: "Ciano Cyberpunk",
    description: "Visual tecnológico de alta densidade e radar",
    hex: "#06b6d4",
    colorType: "solid",
    textClass: "text-cyan-400",
    iconClass: "text-cyan-400",
    textMutedClass: "text-cyan-400/70",
    bgSubtleClass: "bg-cyan-500/10",
    bgSolidClass: "bg-cyan-600 text-white",
    borderClass: "border-cyan-500/40",
    borderHoverClass: "hover:border-cyan-500/60",
    borderSubtleClass: "border-cyan-500/20",
    activeItemClass: "font-black text-cyan-300 bg-cyan-500/15 border border-cyan-500/40 shadow-xs shadow-cyan-500/10 rounded-lg",
    badgeClass: "bg-cyan-500/20 text-cyan-300 border-cyan-500/40",
    ringClass: "ring-cyan-500/40",
    glowClass: "shadow-cyan-500/20",
    itemHoverClass: "hover:text-cyan-400 hover:bg-cyan-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-cyan-400",
  },
  emerald: {
    key: "emerald",
    label: "Esmeralda Matrix",
    description: "Visual de hacking clássico e alta performance",
    hex: "#10b981",
    colorType: "solid",
    textClass: "text-emerald-400",
    iconClass: "text-emerald-400",
    textMutedClass: "text-emerald-400/70",
    bgSubtleClass: "bg-emerald-500/10",
    bgSolidClass: "bg-emerald-600 text-white",
    borderClass: "border-emerald-500/40",
    borderHoverClass: "hover:border-emerald-500/60",
    borderSubtleClass: "border-emerald-500/20",
    activeItemClass: "font-black text-emerald-300 bg-emerald-500/15 border border-emerald-500/40 shadow-xs shadow-emerald-500/10 rounded-lg",
    badgeClass: "bg-emerald-500/20 text-emerald-300 border-emerald-500/40",
    ringClass: "ring-emerald-500/40",
    glowClass: "shadow-emerald-500/20",
    itemHoverClass: "hover:text-emerald-400 hover:bg-emerald-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-emerald-400",
  },
  violet: {
    key: "violet",
    label: "Violeta Neon",
    description: "Estilo sofisticado ultra-moderno e vibrante",
    hex: "#8b5cf6",
    colorType: "solid",
    textClass: "text-violet-400",
    iconClass: "text-violet-400",
    textMutedClass: "text-violet-400/70",
    bgSubtleClass: "bg-violet-500/10",
    bgSolidClass: "bg-violet-600 text-white",
    borderClass: "border-violet-500/40",
    borderHoverClass: "hover:border-violet-500/60",
    borderSubtleClass: "border-violet-500/20",
    activeItemClass: "font-black text-violet-300 bg-violet-500/15 border border-violet-500/40 shadow-xs shadow-violet-500/10 rounded-lg",
    badgeClass: "bg-violet-500/20 text-violet-300 border-violet-500/40",
    ringClass: "ring-violet-500/40",
    glowClass: "shadow-violet-500/20",
    itemHoverClass: "hover:text-violet-400 hover:bg-violet-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-violet-400",
  },
  indigo: {
    key: "indigo",
    label: "Índigo Profundo",
    description: "Design corporativo premium e sóbrio",
    hex: "#6366f1",
    colorType: "solid",
    textClass: "text-indigo-400",
    iconClass: "text-indigo-400",
    textMutedClass: "text-indigo-400/70",
    bgSubtleClass: "bg-indigo-500/10",
    bgSolidClass: "bg-indigo-600 text-white",
    borderClass: "border-indigo-500/40",
    borderHoverClass: "hover:border-indigo-500/60",
    borderSubtleClass: "border-indigo-500/20",
    activeItemClass: "font-black text-indigo-300 bg-indigo-500/15 border border-indigo-500/40 shadow-xs shadow-indigo-500/10 rounded-lg",
    badgeClass: "bg-indigo-500/20 text-indigo-300 border-indigo-500/40",
    ringClass: "ring-indigo-500/40",
    glowClass: "shadow-indigo-500/20",
    itemHoverClass: "hover:text-indigo-400 hover:bg-indigo-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-indigo-400",
  },
  blue: {
    key: "blue",
    label: "Azul Céu Operacional",
    description: "Estilo limpo, analítico e de monitoramento",
    hex: "#0ea5e9",
    colorType: "solid",
    textClass: "text-sky-400",
    iconClass: "text-sky-400",
    textMutedClass: "text-sky-400/70",
    bgSubtleClass: "bg-sky-500/10",
    bgSolidClass: "bg-sky-600 text-white",
    borderClass: "border-sky-500/40",
    borderHoverClass: "hover:border-sky-500/60",
    borderSubtleClass: "border-sky-500/20",
    activeItemClass: "font-black text-sky-300 bg-sky-500/15 border border-sky-500/40 shadow-xs shadow-sky-500/10 rounded-lg",
    badgeClass: "bg-sky-500/20 text-sky-300 border-sky-500/40",
    ringClass: "ring-sky-500/40",
    glowClass: "shadow-sky-500/20",
    itemHoverClass: "hover:text-sky-400 hover:bg-sky-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-sky-400",
  },
  orange: {
    key: "orange",
    label: "Laranja Sunset",
    description: "Energia vibrante, alerta e destaque operacional",
    hex: "#f97316",
    colorType: "solid",
    textClass: "text-orange-400",
    iconClass: "text-orange-400",
    textMutedClass: "text-orange-400/70",
    bgSubtleClass: "bg-orange-500/10",
    bgSolidClass: "bg-orange-600 text-white",
    borderClass: "border-orange-500/40",
    borderHoverClass: "hover:border-orange-500/60",
    borderSubtleClass: "border-orange-500/20",
    activeItemClass: "font-black text-orange-300 bg-orange-500/15 border border-orange-500/40 shadow-xs shadow-orange-500/10 rounded-lg",
    badgeClass: "bg-orange-500/20 text-orange-300 border-orange-500/40",
    ringClass: "ring-orange-500/40",
    glowClass: "shadow-orange-500/20",
    itemHoverClass: "hover:text-orange-400 hover:bg-orange-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-orange-400",
  },
  ruby: {
    key: "ruby",
    label: "Vermelho Rubi Carmesim",
    description: "Tons de combate, impacto tático e destaque agressivo",
    hex: "#ef4444",
    colorType: "solid",
    textClass: "text-red-400",
    iconClass: "text-red-400",
    textMutedClass: "text-red-400/70",
    bgSubtleClass: "bg-red-500/10",
    bgSolidClass: "bg-red-600 text-white",
    borderClass: "border-red-500/40",
    borderHoverClass: "hover:border-red-500/60",
    borderSubtleClass: "border-red-500/20",
    activeItemClass: "font-black text-red-300 bg-red-500/15 border border-red-500/40 shadow-xs shadow-red-500/10 rounded-lg",
    badgeClass: "bg-red-500/20 text-red-300 border-red-500/40",
    ringClass: "ring-red-500/40",
    glowClass: "shadow-red-500/20",
    itemHoverClass: "hover:text-red-400 hover:bg-red-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-red-400",
  },
  fuchsia: {
    key: "fuchsia",
    label: "Fúcsia Shock Elétrico",
    description: "Visual cyberpunk ultra luminoso e contrastante",
    hex: "#d946ef",
    colorType: "solid",
    textClass: "text-fuchsia-400",
    iconClass: "text-fuchsia-400",
    textMutedClass: "text-fuchsia-400/70",
    bgSubtleClass: "bg-fuchsia-500/10",
    bgSolidClass: "bg-fuchsia-600 text-white",
    borderClass: "border-fuchsia-500/40",
    borderHoverClass: "hover:border-fuchsia-500/60",
    borderSubtleClass: "border-fuchsia-500/20",
    activeItemClass: "font-black text-fuchsia-300 bg-fuchsia-500/15 border border-fuchsia-500/40 shadow-xs shadow-fuchsia-500/10 rounded-lg",
    badgeClass: "bg-fuchsia-500/20 text-fuchsia-300 border-fuchsia-500/40",
    ringClass: "ring-fuchsia-500/40",
    glowClass: "shadow-fuchsia-500/20",
    itemHoverClass: "hover:text-fuchsia-400 hover:bg-fuchsia-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-fuchsia-400",
  },
  purple: {
    key: "purple",
    label: "Púrpura Real Imperial",
    description: "Elegância refinada e mística de alta patente",
    hex: "#a855f7",
    colorType: "solid",
    textClass: "text-purple-400",
    iconClass: "text-purple-400",
    textMutedClass: "text-purple-400/70",
    bgSubtleClass: "bg-purple-500/10",
    bgSolidClass: "bg-purple-600 text-white",
    borderClass: "border-purple-500/40",
    borderHoverClass: "hover:border-purple-500/60",
    borderSubtleClass: "border-purple-500/20",
    activeItemClass: "font-black text-purple-300 bg-purple-500/15 border border-purple-500/40 shadow-xs shadow-purple-500/10 rounded-lg",
    badgeClass: "bg-purple-500/20 text-purple-300 border-purple-500/40",
    ringClass: "ring-purple-500/40",
    glowClass: "shadow-purple-500/20",
    itemHoverClass: "hover:text-purple-400 hover:bg-purple-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-purple-400",
  },
  lime: {
    key: "lime",
    label: "Verde Limão Biohazard",
    description: "Radiação neon de alerta extremo e destaque ágil",
    hex: "#84cc16",
    colorType: "solid",
    textClass: "text-lime-400",
    iconClass: "text-lime-400",
    textMutedClass: "text-lime-400/70",
    bgSubtleClass: "bg-lime-500/10",
    bgSolidClass: "bg-lime-500 text-zinc-950 font-bold",
    borderClass: "border-lime-500/40",
    borderHoverClass: "hover:border-lime-500/60",
    borderSubtleClass: "border-lime-500/20",
    activeItemClass: "font-black text-lime-300 bg-lime-500/15 border border-lime-500/40 shadow-xs shadow-lime-500/10 rounded-lg",
    badgeClass: "bg-lime-500/20 text-lime-300 border-lime-500/40",
    ringClass: "ring-lime-500/40",
    glowClass: "shadow-lime-500/20",
    itemHoverClass: "hover:text-lime-400 hover:bg-lime-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-lime-400",
  },
  teal: {
    key: "teal",
    label: "Turquesa Oceânica",
    description: "Equilíbrio moderno entre ciano ártico e menta",
    hex: "#14b8a6",
    colorType: "solid",
    textClass: "text-teal-400",
    iconClass: "text-teal-400",
    textMutedClass: "text-teal-400/70",
    bgSubtleClass: "bg-teal-500/10",
    bgSolidClass: "bg-teal-600 text-white",
    borderClass: "border-teal-500/40",
    borderHoverClass: "hover:border-teal-500/60",
    borderSubtleClass: "border-teal-500/20",
    activeItemClass: "font-black text-teal-300 bg-teal-500/15 border border-teal-500/40 shadow-xs shadow-teal-500/10 rounded-lg",
    badgeClass: "bg-teal-500/20 text-teal-300 border-teal-500/40",
    ringClass: "ring-teal-500/40",
    glowClass: "shadow-teal-500/20",
    itemHoverClass: "hover:text-teal-400 hover:bg-teal-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-teal-400",
  },
  yellow: {
    key: "yellow",
    label: "Amarelo Solar Neon",
    description: "Luminosidade pura, atenção e contraste visual",
    hex: "#eab308",
    colorType: "solid",
    textClass: "text-yellow-400",
    iconClass: "text-yellow-400",
    textMutedClass: "text-yellow-400/70",
    bgSubtleClass: "bg-yellow-500/10",
    bgSolidClass: "bg-yellow-500 text-black font-bold",
    borderClass: "border-yellow-500/40",
    borderHoverClass: "hover:border-yellow-500/60",
    borderSubtleClass: "border-yellow-500/20",
    activeItemClass: "font-black text-yellow-300 bg-yellow-500/15 border border-yellow-500/40 shadow-xs shadow-yellow-500/10 rounded-lg",
    badgeClass: "bg-yellow-500/20 text-yellow-300 border-yellow-500/40",
    ringClass: "ring-yellow-500/40",
    glowClass: "shadow-yellow-500/20",
    itemHoverClass: "hover:text-yellow-400 hover:bg-yellow-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-yellow-400",
  },
  slate: {
    key: "slate",
    label: "Grafite Titânio Cyber",
    description: "Minimalismo fosco escuro, furtivo e tático",
    hex: "#64748b",
    colorType: "solid",
    textClass: "text-slate-300",
    iconClass: "text-slate-300",
    textMutedClass: "text-slate-400/70",
    bgSubtleClass: "bg-slate-500/15",
    bgSolidClass: "bg-slate-700 text-white font-semibold",
    borderClass: "border-slate-500/40",
    borderHoverClass: "hover:border-slate-400",
    borderSubtleClass: "border-slate-500/20",
    activeItemClass: "font-black text-slate-200 bg-slate-500/20 border border-slate-400/40 shadow-xs shadow-slate-500/10 rounded-lg",
    badgeClass: "bg-slate-500/20 text-slate-200 border-slate-500/40",
    ringClass: "ring-slate-400/40",
    glowClass: "shadow-slate-500/20",
    itemHoverClass: "hover:text-slate-200 hover:bg-slate-500/15",
    itemIconHoverClass: "group-hover/menuitem:text-slate-200",
  },

  // ─── CORES PEROLADAS (EFEITO PÉROLA IRIDESCENTE) ───
  "pearl-white": {
    key: "pearl-white",
    label: "Pérola Branca Holográfica",
    description: "Brilho puro madrepérola com reflexos holográficos suaves",
    hex: "#f8fafc",
    previewGradient: "linear-gradient(135deg, #ffffff 0%, #e2e8f0 35%, #ddd6fe 70%, #fbcfe8 100%)",
    colorType: "pearl",
    textClass: "text-zinc-100",
    iconClass: "text-zinc-200",
    textMutedClass: "text-zinc-300/80",
    bgSubtleClass: "bg-white/10",
    bgSolidClass: "bg-gradient-to-r from-slate-100 via-purple-100 to-pink-100 text-zinc-950 font-black",
    borderClass: "border-white/40",
    borderHoverClass: "hover:border-white/70",
    borderSubtleClass: "border-white/20",
    activeItemClass: "font-black text-white bg-white/20 border border-white/50 shadow-sm shadow-white/25 rounded-lg backdrop-blur-xs",
    badgeClass: "bg-white/20 text-white border-white/40",
    ringClass: "ring-white/50",
    glowClass: "shadow-white/25",
    itemHoverClass: "hover:text-white hover:bg-white/10",
    itemIconHoverClass: "group-hover/menuitem:text-white",
  },
  "pearl-black": {
    key: "pearl-black",
    label: "Pérola Negra Ônix",
    description: "Madrepérola escura com reflexos metálicos violeta e índigo",
    hex: "#18181b",
    previewGradient: "linear-gradient(135deg, #27272a 0%, #3f3f46 40%, #1e1b4b 75%, #09090b 100%)",
    colorType: "pearl",
    textClass: "text-zinc-200",
    iconClass: "text-zinc-300",
    textMutedClass: "text-zinc-400/80",
    bgSubtleClass: "bg-zinc-800/60",
    bgSolidClass: "bg-gradient-to-r from-zinc-800 via-indigo-950 to-zinc-900 text-white font-black border border-zinc-700",
    borderClass: "border-zinc-500/50",
    borderHoverClass: "hover:border-zinc-400",
    borderSubtleClass: "border-zinc-700/50",
    activeItemClass: "font-black text-zinc-100 bg-zinc-800/80 border border-zinc-500/60 shadow-sm shadow-zinc-900/60 rounded-lg",
    badgeClass: "bg-zinc-800 text-zinc-200 border-zinc-600",
    ringClass: "ring-zinc-400/50",
    glowClass: "shadow-zinc-700/30",
    itemHoverClass: "hover:text-zinc-100 hover:bg-zinc-800/50",
    itemIconHoverClass: "group-hover/menuitem:text-zinc-200",
  },
  "pearl-rose": {
    key: "pearl-rose",
    label: "Pérola Rosa Quartzo",
    description: "Iridescência mineral rosada com nuances douradas e acetinadas",
    hex: "#fb7185",
    previewGradient: "linear-gradient(135deg, #fff1f2 0%, #f472b6 45%, #fda4af 80%, #fed7aa 100%)",
    colorType: "pearl",
    textClass: "text-pink-300",
    iconClass: "text-pink-400",
    textMutedClass: "text-pink-300/75",
    bgSubtleClass: "bg-pink-500/10",
    bgSolidClass: "bg-gradient-to-r from-pink-300 via-rose-300 to-amber-200 text-zinc-950 font-black",
    borderClass: "border-pink-400/40",
    borderHoverClass: "hover:border-pink-400/70",
    borderSubtleClass: "border-pink-400/20",
    activeItemClass: "font-black text-pink-200 bg-pink-500/15 border border-pink-400/40 shadow-xs shadow-pink-500/20 rounded-lg",
    badgeClass: "bg-pink-500/20 text-pink-200 border-pink-400/40",
    ringClass: "ring-pink-400/40",
    glowClass: "shadow-pink-500/20",
    itemHoverClass: "hover:text-pink-300 hover:bg-pink-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-pink-300",
  },
  "pearl-gold": {
    key: "pearl-gold",
    label: "Pérola Champagne Ouro",
    description: "Lustro nobre de champagne perolado com reflexos sedosos",
    hex: "#fde047",
    previewGradient: "linear-gradient(135deg, #fffbeb 0%, #fef08a 35%, #f59e0b 75%, #fde68a 100%)",
    colorType: "pearl",
    textClass: "text-amber-300",
    iconClass: "text-amber-400",
    textMutedClass: "text-amber-300/75",
    bgSubtleClass: "bg-amber-500/10",
    bgSolidClass: "bg-gradient-to-r from-amber-200 via-yellow-300 to-amber-400 text-zinc-950 font-black",
    borderClass: "border-amber-400/40",
    borderHoverClass: "hover:border-amber-400/70",
    borderSubtleClass: "border-amber-400/20",
    activeItemClass: "font-black text-amber-200 bg-amber-500/15 border border-amber-400/40 shadow-xs shadow-amber-500/20 rounded-lg",
    badgeClass: "bg-amber-500/20 text-amber-200 border-amber-400/40",
    ringClass: "ring-amber-400/40",
    glowClass: "shadow-amber-500/20",
    itemHoverClass: "hover:text-amber-300 hover:bg-amber-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-amber-300",
  },
  "pearl-cyan": {
    key: "pearl-cyan",
    label: "Pérola Azul Celestial",
    description: "Ciano ártico perolado com reflexos cristalinos e lilás suave",
    hex: "#38bdf8",
    previewGradient: "linear-gradient(135deg, #f0fdfa 0%, #7dd3fc 40%, #818cf8 80%, #c4b5fd 100%)",
    colorType: "pearl",
    textClass: "text-sky-300",
    iconClass: "text-sky-400",
    textMutedClass: "text-sky-300/75",
    bgSubtleClass: "bg-sky-500/10",
    bgSolidClass: "bg-gradient-to-r from-sky-200 via-cyan-300 to-indigo-300 text-zinc-950 font-black",
    borderClass: "border-sky-400/40",
    borderHoverClass: "hover:border-sky-400/70",
    borderSubtleClass: "border-sky-400/20",
    activeItemClass: "font-black text-sky-200 bg-sky-500/15 border border-sky-400/40 shadow-xs shadow-sky-500/20 rounded-lg",
    badgeClass: "bg-sky-500/20 text-sky-200 border-sky-400/40",
    ringClass: "ring-sky-400/40",
    glowClass: "shadow-sky-500/20",
    itemHoverClass: "hover:text-sky-300 hover:bg-sky-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-sky-300",
  },
  "pearl-jade": {
    key: "pearl-jade",
    label: "Pérola Verde Jade",
    description: "Madrepérola verde menta com iridescência de jade oriental",
    hex: "#34d399",
    previewGradient: "linear-gradient(135deg, #f0fdf4 0%, #6ee7b7 40%, #2dd4bf 75%, #a7f3d0 100%)",
    colorType: "pearl",
    textClass: "text-emerald-300",
    iconClass: "text-emerald-400",
    textMutedClass: "text-emerald-300/75",
    bgSubtleClass: "bg-emerald-500/10",
    bgSolidClass: "bg-gradient-to-r from-emerald-200 via-teal-300 to-green-300 text-zinc-950 font-black",
    borderClass: "border-emerald-400/40",
    borderHoverClass: "hover:border-emerald-400/70",
    borderSubtleClass: "border-emerald-400/20",
    activeItemClass: "font-black text-emerald-200 bg-emerald-500/15 border border-emerald-400/40 shadow-xs shadow-emerald-500/20 rounded-lg",
    badgeClass: "bg-emerald-500/20 text-emerald-200 border-emerald-400/40",
    ringClass: "ring-emerald-400/40",
    glowClass: "shadow-emerald-500/20",
    itemHoverClass: "hover:text-emerald-300 hover:bg-emerald-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-emerald-300",
  },
  "pearl-lavender": {
    key: "pearl-lavender",
    label: "Pérola Lavanda Mística",
    description: "Nuance perolada violeta com brilho holográfico etéreo",
    hex: "#c084fc",
    previewGradient: "linear-gradient(135deg, #faf5ff 0%, #d8b4fe 40%, #f472b6 75%, #e9d5ff 100%)",
    colorType: "pearl",
    textClass: "text-purple-300",
    iconClass: "text-purple-400",
    textMutedClass: "text-purple-300/75",
    bgSubtleClass: "bg-purple-500/10",
    bgSolidClass: "bg-gradient-to-r from-purple-200 via-fuchsia-300 to-pink-200 text-zinc-950 font-black",
    borderClass: "border-purple-400/40",
    borderHoverClass: "hover:border-purple-400/70",
    borderSubtleClass: "border-purple-400/20",
    activeItemClass: "font-black text-purple-200 bg-purple-500/15 border border-purple-400/40 shadow-xs shadow-purple-500/20 rounded-lg",
    badgeClass: "bg-purple-500/20 text-purple-200 border-purple-400/40",
    ringClass: "ring-purple-400/40",
    glowClass: "shadow-purple-500/20",
    itemHoverClass: "hover:text-purple-300 hover:bg-purple-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-purple-300",
  },

  // ─── DEGRADÊS & GRADIENTES ───
  "gradient-cyber": {
    key: "gradient-cyber",
    label: "Degradê Cyberpunk Neon",
    description: "Fusão de alta energia do rosa choque ao ciano elétrico",
    hex: "#06b6d4",
    previewGradient: "linear-gradient(135deg, #ec4899 0%, #06b6d4 100%)",
    colorType: "gradient",
    textClass: "text-cyan-400",
    iconClass: "text-cyan-400",
    textMutedClass: "text-cyan-400/75",
    bgSubtleClass: "bg-gradient-to-r from-pink-500/10 to-cyan-500/10",
    bgSolidClass: "bg-gradient-to-r from-pink-500 to-cyan-500 text-white font-black",
    borderClass: "border-cyan-500/40",
    borderHoverClass: "hover:border-cyan-400",
    borderSubtleClass: "border-pink-500/30",
    activeItemClass: "font-black text-white bg-gradient-to-r from-pink-500/30 to-cyan-500/30 border border-cyan-400/50 shadow-xs shadow-cyan-500/20 rounded-lg",
    badgeClass: "bg-gradient-to-r from-pink-500/25 to-cyan-500/25 text-cyan-200 border-cyan-400/40",
    ringClass: "ring-cyan-400/40",
    glowClass: "shadow-cyan-500/25",
    itemHoverClass: "hover:text-cyan-300 hover:bg-gradient-to-r hover:from-pink-500/10 hover:to-cyan-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-cyan-300",
  },
  "gradient-sunset": {
    key: "gradient-sunset",
    label: "Degradê Sunset Synthwave",
    description: "Pôr do sol retrô com fusão de laranja solar e fúcsia",
    hex: "#f97316",
    previewGradient: "linear-gradient(135deg, #f97316 0%, #ec4899 100%)",
    colorType: "gradient",
    textClass: "text-orange-400",
    iconClass: "text-orange-400",
    textMutedClass: "text-orange-400/75",
    bgSubtleClass: "bg-gradient-to-r from-orange-500/10 to-pink-500/10",
    bgSolidClass: "bg-gradient-to-r from-orange-500 to-pink-500 text-white font-black",
    borderClass: "border-orange-500/40",
    borderHoverClass: "hover:border-orange-400",
    borderSubtleClass: "border-pink-500/30",
    activeItemClass: "font-black text-white bg-gradient-to-r from-orange-500/30 to-pink-500/30 border border-orange-400/50 shadow-xs shadow-orange-500/20 rounded-lg",
    badgeClass: "bg-gradient-to-r from-orange-500/25 to-pink-500/25 text-orange-200 border-orange-400/40",
    ringClass: "ring-orange-400/40",
    glowClass: "shadow-orange-500/25",
    itemHoverClass: "hover:text-orange-300 hover:bg-gradient-to-r hover:from-orange-500/10 hover:to-pink-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-orange-300",
  },
  "gradient-aurora": {
    key: "gradient-aurora",
    label: "Degradê Aurora Boreal",
    description: "Ondas polares luminosas do verde esmeralda ao azul turquesa",
    hex: "#10b981",
    previewGradient: "linear-gradient(135deg, #10b981 0%, #06b6d4 100%)",
    colorType: "gradient",
    textClass: "text-emerald-400",
    iconClass: "text-emerald-400",
    textMutedClass: "text-emerald-400/75",
    bgSubtleClass: "bg-gradient-to-r from-emerald-500/10 to-cyan-500/10",
    bgSolidClass: "bg-gradient-to-r from-emerald-500 to-cyan-500 text-white font-black",
    borderClass: "border-emerald-500/40",
    borderHoverClass: "hover:border-emerald-400",
    borderSubtleClass: "border-cyan-500/30",
    activeItemClass: "font-black text-white bg-gradient-to-r from-emerald-500/30 to-cyan-500/30 border border-emerald-400/50 shadow-xs shadow-emerald-500/20 rounded-lg",
    badgeClass: "bg-gradient-to-r from-emerald-500/25 to-cyan-500/25 text-emerald-200 border-emerald-400/40",
    ringClass: "ring-emerald-400/40",
    glowClass: "shadow-emerald-500/25",
    itemHoverClass: "hover:text-emerald-300 hover:bg-gradient-to-r hover:from-emerald-500/10 hover:to-cyan-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-emerald-300",
  },
  "gradient-galaxy": {
    key: "gradient-galaxy",
    label: "Degradê Galáxia Cósmica",
    description: "Nebulosa do espaço profundo de índigo, violeta e magenta",
    hex: "#a855f7",
    previewGradient: "linear-gradient(135deg, #6366f1 0%, #a855f7 50%, #ec4899 100%)",
    colorType: "gradient",
    textClass: "text-purple-400",
    iconClass: "text-purple-400",
    textMutedClass: "text-purple-400/75",
    bgSubtleClass: "bg-gradient-to-r from-indigo-500/10 to-pink-500/10",
    bgSolidClass: "bg-gradient-to-r from-indigo-500 via-purple-500 to-pink-500 text-white font-black",
    borderClass: "border-purple-500/40",
    borderHoverClass: "hover:border-purple-400",
    borderSubtleClass: "border-pink-500/30",
    activeItemClass: "font-black text-white bg-gradient-to-r from-indigo-500/30 to-pink-500/30 border border-purple-400/50 shadow-xs shadow-purple-500/20 rounded-lg",
    badgeClass: "bg-gradient-to-r from-indigo-500/25 to-pink-500/25 text-purple-200 border-purple-400/40",
    ringClass: "ring-purple-400/40",
    glowClass: "shadow-purple-500/25",
    itemHoverClass: "hover:text-purple-300 hover:bg-gradient-to-r hover:from-indigo-500/10 hover:to-pink-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-purple-300",
  },
  "gradient-fire": {
    key: "gradient-fire",
    label: "Degradê Fogo Quântico",
    description: "Chama de alta energia do carmesim vivo ao laranja e ouro",
    hex: "#ef4444",
    previewGradient: "linear-gradient(135deg, #ef4444 0%, #f97316 60%, #facc15 100%)",
    colorType: "gradient",
    textClass: "text-red-400",
    iconClass: "text-red-400",
    textMutedClass: "text-red-400/75",
    bgSubtleClass: "bg-gradient-to-r from-red-500/10 to-amber-500/10",
    bgSolidClass: "bg-gradient-to-r from-red-500 via-orange-500 to-amber-400 text-white font-black",
    borderClass: "border-red-500/40",
    borderHoverClass: "hover:border-red-400",
    borderSubtleClass: "border-amber-500/30",
    activeItemClass: "font-black text-white bg-gradient-to-r from-red-500/30 to-amber-500/30 border border-red-400/50 shadow-xs shadow-red-500/20 rounded-lg",
    badgeClass: "bg-gradient-to-r from-red-500/25 to-amber-500/25 text-amber-200 border-red-400/40",
    ringClass: "ring-red-400/40",
    glowClass: "shadow-red-500/25",
    itemHoverClass: "hover:text-red-300 hover:bg-gradient-to-r hover:from-red-500/10 hover:to-amber-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-red-300",
  },
  "gradient-hyper": {
    key: "gradient-hyper",
    label: "Degradê Hiperdrive",
    description: "Velocidade da luz do azul cobalto ao índigo e violeta",
    hex: "#0284c7",
    previewGradient: "linear-gradient(135deg, #0284c7 0%, #6366f1 60%, #a855f7 100%)",
    colorType: "gradient",
    textClass: "text-sky-400",
    iconClass: "text-sky-400",
    textMutedClass: "text-sky-400/75",
    bgSubtleClass: "bg-gradient-to-r from-sky-500/10 to-violet-500/10",
    bgSolidClass: "bg-gradient-to-r from-sky-500 via-indigo-500 to-purple-500 text-white font-black",
    borderClass: "border-sky-500/40",
    borderHoverClass: "hover:border-sky-400",
    borderSubtleClass: "border-purple-500/30",
    activeItemClass: "font-black text-white bg-gradient-to-r from-sky-500/30 to-purple-500/30 border border-sky-400/50 shadow-xs shadow-sky-500/20 rounded-lg",
    badgeClass: "bg-gradient-to-r from-sky-500/25 to-purple-500/25 text-sky-200 border-sky-400/40",
    ringClass: "ring-sky-400/40",
    glowClass: "shadow-sky-500/25",
    itemHoverClass: "hover:text-sky-300 hover:bg-gradient-to-r hover:from-sky-500/10 hover:to-purple-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-sky-300",
  },
  "gradient-gold": {
    key: "gradient-gold",
    label: "Degradê Ouro Imperial",
    description: "Gradiente da alta nobreza do ouro polido ao âmbar bronze",
    hex: "#fbbf24",
    previewGradient: "linear-gradient(135deg, #fbbf24 0%, #d97706 70%, #78350f 100%)",
    colorType: "gradient",
    textClass: "text-amber-300",
    iconClass: "text-amber-400",
    textMutedClass: "text-amber-300/75",
    bgSubtleClass: "bg-gradient-to-r from-yellow-500/10 to-amber-600/10",
    bgSolidClass: "bg-gradient-to-r from-amber-300 via-amber-500 to-yellow-600 text-zinc-950 font-black",
    borderClass: "border-amber-400/40",
    borderHoverClass: "hover:border-amber-400",
    borderSubtleClass: "border-amber-500/30",
    activeItemClass: "font-black text-amber-200 bg-gradient-to-r from-amber-500/30 to-yellow-600/30 border border-amber-400/50 shadow-xs shadow-amber-500/20 rounded-lg",
    badgeClass: "bg-gradient-to-r from-amber-500/25 to-yellow-600/25 text-amber-200 border-amber-400/40",
    ringClass: "ring-amber-400/40",
    glowClass: "shadow-amber-500/25",
    itemHoverClass: "hover:text-amber-200 hover:bg-gradient-to-r hover:from-yellow-500/10 hover:to-amber-600/10",
    itemIconHoverClass: "group-hover/menuitem:text-amber-300",
  },
  "gradient-matrix": {
    key: "gradient-matrix",
    label: "Degradê Matrix Hacker",
    description: "Fluxo de terminal do verde limão neon à floresta esmeralda",
    hex: "#84cc16",
    previewGradient: "linear-gradient(135deg, #84cc16 0%, #10b981 60%, #065f46 100%)",
    colorType: "gradient",
    textClass: "text-lime-400",
    iconClass: "text-lime-400",
    textMutedClass: "text-lime-400/75",
    bgSubtleClass: "bg-gradient-to-r from-lime-500/10 to-emerald-500/10",
    bgSolidClass: "bg-gradient-to-r from-lime-500 to-emerald-600 text-zinc-950 font-black",
    borderClass: "border-lime-500/40",
    borderHoverClass: "hover:border-lime-400",
    borderSubtleClass: "border-emerald-500/30",
    activeItemClass: "font-black text-lime-200 bg-gradient-to-r from-lime-500/30 to-emerald-600/30 border border-lime-400/50 shadow-xs shadow-lime-500/20 rounded-lg",
    badgeClass: "bg-gradient-to-r from-lime-500/25 to-emerald-600/25 text-lime-200 border-lime-400/40",
    ringClass: "ring-lime-400/40",
    glowClass: "shadow-lime-500/25",
    itemHoverClass: "hover:text-lime-300 hover:bg-gradient-to-r hover:from-lime-500/10 hover:to-emerald-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-lime-300",
  },
  "gradient-amethyst": {
    key: "gradient-amethyst",
    label: "Degradê Ametista Real",
    description: "Cristal ametista sofisticado do roxo profundo ao lavanda",
    hex: "#7c3aed",
    previewGradient: "linear-gradient(135deg, #7c3aed 0%, #c084fc 100%)",
    colorType: "gradient",
    textClass: "text-violet-400",
    iconClass: "text-violet-400",
    textMutedClass: "text-violet-400/75",
    bgSubtleClass: "bg-gradient-to-r from-violet-500/10 to-purple-500/10",
    bgSolidClass: "bg-gradient-to-r from-violet-600 to-purple-400 text-white font-black",
    borderClass: "border-violet-500/40",
    borderHoverClass: "hover:border-violet-400",
    borderSubtleClass: "border-purple-500/30",
    activeItemClass: "font-black text-white bg-gradient-to-r from-violet-500/30 to-purple-500/30 border border-violet-400/50 shadow-xs shadow-violet-500/20 rounded-lg",
    badgeClass: "bg-gradient-to-r from-violet-500/25 to-purple-500/25 text-violet-200 border-violet-400/40",
    ringClass: "ring-violet-400/40",
    glowClass: "shadow-violet-500/25",
    itemHoverClass: "hover:text-violet-300 hover:bg-gradient-to-r hover:from-violet-500/10 hover:to-purple-500/10",
    itemIconHoverClass: "group-hover/menuitem:text-violet-300",
  },
};

export function getPanelColorStyle(color?: string | null, fallback: PanelColor = "rose"): PanelColorStyle {
  if (color && color in PANEL_COLOR_STYLES) {
    return PANEL_COLOR_STYLES[color as PanelColor];
  }
  if (fallback in PANEL_COLOR_STYLES) {
    return PANEL_COLOR_STYLES[fallback];
  }
  return PANEL_COLOR_STYLES.rose;
}

/* ─── Category Icon Registry ─── */
export const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
  Terminal,
  Crown,
  FolderTree,
  Code2,
  Sliders,
  Bot,
  Webhook,
  Shield,
  ShieldCheck,
  Sparkles,
  TrendingUp,
  Boxes,
  Users,
  Settings,
  Zap,
  Landmark,
  Workflow,
  Target,
  Radio,
  Eye,
  ScrollText,
  Flame,
  Activity,
  Layers,
  Cpu,
  Wrench,
  KeyRound,
  LayoutDashboard,
  Server,
  FileCode,
  Gauge,
  Database,
  Lock,
};

export const POPULAR_CATEGORY_ICONS: { name: string; label: string; icon: LucideIcon }[] = [
  { name: "Terminal", label: "Terminal / Console", icon: Terminal },
  { name: "Crown", label: "Coroa Executiva", icon: Crown },
  { name: "Code2", label: "Código / Dev", icon: Code2 },
  { name: "FolderTree", label: "Árvore de Pastas", icon: FolderTree },
  { name: "Sliders", label: "Controles & Sliders", icon: Sliders },
  { name: "Bot", label: "Bot Discord", icon: Bot },
  { name: "Webhook", label: "Webhook", icon: Webhook },
  { name: "ShieldCheck", label: "Segurança / Cargos", icon: ShieldCheck },
  { name: "Sparkles", label: "Destaque / Novidades", icon: Sparkles },
  { name: "TrendingUp", label: "Métricas & Crescimento", icon: TrendingUp },
  { name: "Boxes", label: "Inventário & Baús", icon: Boxes },
  { name: "Users", label: "Membros & Equipe", icon: Users },
  { name: "Landmark", label: "Finanças & Caixa", icon: Landmark },
  { name: "Settings", label: "Configurações", icon: Settings },
  { name: "Zap", label: "Automação / Raio", icon: Zap },
  { name: "Radio", label: "Transmissões & Lives", icon: Radio },
  { name: "Gauge", label: "Diagnóstico / Velocidade", icon: Gauge },
  { name: "Database", label: "Banco de Dados", icon: Database },
  { name: "Server", label: "Servidores", icon: Server },
  { name: "Layers", label: "Camadas & Módulos", icon: Layers },
];

export function resolveCategoryIcon(
  iconName?: string | null,
  fallback: LucideIcon = FolderTree
): LucideIcon {
  if (iconName && iconName in CATEGORY_ICON_MAP) {
    return CATEGORY_ICON_MAP[iconName];
  }
  return fallback;
}
