import type { LucideIcon } from "lucide-react";
import {
  Workflow,
  LayoutDashboard,
  ArrowLeftRight,
  ShoppingCart,
  MessageSquare,
  Boxes,
  Users,
  Landmark,
  Trophy,
  TrendingUp,
  Target,
  CalendarOff,
  ShieldCheck,
  Settings,
  Megaphone,
  ScrollText,
  Wrench,
  User,
  Sparkles,
  LifeBuoy,
  Bell,
  BellRing,
  Crown,
  Bot,
  Webhook,
  Code2,
  Radio,
  PackageCheck,
} from "lucide-react";
import type { Permission } from "@/lib/permissions";

export type PermissionDetail = {
  key: Permission;
  label: string;
  description: string;
  badge?: string;
  importantNote?: string;
};

export type PageCardConfig = {
  id: string;
  title: string;
  route: string;
  icon: LucideIcon;
  description: string;
  color: string;
  defaultCat: string;
  defaultOrder: number;
  permissions: PermissionDetail[];
};

export const READ_ONLY_PERMISSIONS: Permission[] = [
  "view_dashboard",
  "view_cash_fund",
  "view_stock",
  "view_stock_management",
  "view_baus",
  "view_all_movements",
  "view_movements",
  "view_movement_balances",
  "view_movement_baus",
  "view_sales",
  "view_products",
  "view_categories",
  "view_members",
  "view_sensitive_data",
  "view_consolidated_financials",
  "view_rankings",
  "view_performance",
  "view_goals",
  "view_absences",
  "view_all_absences",
  "view_hierarchy",
  "view_audit",
  "view_patch_notes",
  "view_profile",
  "view_chat",
  "view_tickets",
  "view_all_tickets",
  "view_notifications",
  "view_ceo_notifications",
  "view_dev_notifications",
  "view_lives",
  "view_stream_logs",
];

export const PAGE_CARDS: PageCardConfig[] = [
  {
    id: "hierarquia",
    title: "Hierarquia do Grupo",
    route: "/hierarquia",
    icon: Workflow,
    description: "Visualização inovadora, minimalista e interativa da estrutura de comando e cargos do grupo.",
    color: "border-purple-500/40 bg-purple-500/5 text-purple-400",
    defaultCat: "Gestão",
    defaultOrder: 0,
    permissions: [
      {
        key: "view_hierarchy",
        label: "Visualizar Árvore de Hierarquia",
        description: "Permite acessar a rota /hierarquia e visualizar a árvore completa de cargos e membros do grupo.",
      },
      {
        key: "manage_hierarchy",
        label: "Gerenciar Estrutura de Hierarquia",
        description: "Permite reordenar a estrutura e gerenciar limites de vagas por patente.",
        badge: "Gestão de Cargos",
      },
    ],
  },
  {
    id: "dashboard",
    title: "Dashboard",
    route: "/dashboard",
    icon: LayoutDashboard,
    description: "Tela inicial da plataforma com comunicados em destaque, membros online e resumo geral.",
    color: "border-indigo-500/40 bg-indigo-500/5 text-indigo-400",
    defaultCat: "Operação",
    defaultOrder: 0,
    permissions: [
      {
        key: "view_dashboard",
        label: "Visualizar Dashboard",
        description: "Permite acessar a tela inicial da plataforma Twin Wheels.",
      },
    ],
  },
  {
    id: "movimentacoes",
    title: "Movimentações de Estoque",
    route: "/movimentacoes",
    icon: ArrowLeftRight,
    description: "Histórico completo de entradas e saídas de itens com filtro por baú, membro e data.",
    color: "border-sky-500/40 bg-sky-500/5 text-sky-400",
    defaultCat: "Operação",
    defaultOrder: 1,
    permissions: [
      {
        key: "view_movements",
        label: "Ver Página de Movimentação",
        description: "Permite acessar a rota /movimentacoes para visualizar a tela de movimentações de estoque.",
        badge: "Acesso à Rota",
      },
      {
        key: "view_all_movements",
        label: "Ver Histórico de Lançamentos",
        description: "Visualizar a seção de Histórico de Lançamentos com todos os registros de entrada e saída feitos pelos membros.",
      },
      {
        key: "view_movement_balances",
        label: "Ver Saldos (Anterior e Resultante)",
        description: "Permite visualizar as colunas numéricas de saldo em estoque antes e depois de cada movimentação.",
        badge: "Saldos Estoque",
      },
      {
        key: "view_movement_baus",
        label: "Ver Identificação dos Baús e Depósitos",
        description: "Permite visualizar qual baú/depósito de origem e destino foi selecionado no lançamento.",
        badge: "Identificação Baús",
      },
      {
        key: "create_movement",
        label: "Registrar Movimentações de Estoque",
        description: "Dar entrada (+) ou saída (-) de insumos nos baús da facção.",
      },
      {
        key: "reverse_movement",
        label: "Estornar Movimentações de Estoque",
        description: "Permite estornar lançamentos de estoque feitos por engano.",
        badge: "Estorno Estoque",
      },
      {
        key: "delete_movement",
        label: "Apagar Lançamentos de Estoque",
        description: "Permite deletar permanentemente um registro de movimentação de estoque.",
        badge: "Ação Crítica",
      },
    ],
  },
  {
    id: "vendas",
    title: "Registro de Vendas",
    route: "/vendas",
    icon: ShoppingCart,
    description: "Lançamento e controle de vendas de produtos com cálculo automático de receita e comissões.",
    color: "border-emerald-500/40 bg-emerald-500/5 text-emerald-400",
    defaultCat: "Operação",
    defaultOrder: 2,
    permissions: [
      {
        key: "view_sales",
        label: "Visualizar Histórico de Vendas",
        description: "Ver todas as vendas efetuadas pelos membros da facção.",
      },
      {
        key: "create_sale",
        label: "Registrar Novas Vendas",
        description: "Permite efetuar lançamentos de vendas e movimentar faturamento.",
      },
      {
        key: "reverse_sale",
        label: "Estornar Registros de Vendas",
        description: "Permite cancelar/estornar uma venda incorreta.",
        badge: "Estorno Vendas",
      },
      {
        key: "delete_sale",
        label: "Apagar Registros de Vendas",
        description: "Permite apagar definitivamente um lançamento de venda do sistema.",
        badge: "Ação Crítica",
      },
    ],
  },
  {
    id: "lives",
    title: "Transmissões & Lives",
    route: "/lives",
    icon: Radio,
    description: "Central de transmissões ao vivo da facção, detecção automática de streamers, vinculação de contas e notificações em tempo real.",
    color: "border-rose-500/40 bg-rose-500/5 text-rose-400",
    defaultCat: "Operação",
    defaultOrder: 3,
    permissions: [
      {
        key: "view_lives",
        label: "Visualizar Lives e Transmissões (/lives)",
        description: "Permite acessar a página /lives, assistir streamers e receber alertas em tempo real.",
        badge: "Acesso à Rota",
      },
      {
        key: "link_stream_account",
        label: "Vincular Contas de Transmissão",
        description: "Permite ao membro conectar e desconectar seus próprios canais de streaming (Twitch, Kick, YouTube, TikTok).",
        badge: "Vinculação",
      },
      {
        key: "manage_stream_accounts",
        label: "Gerenciar Contas de Streamers",
        description: "Permite à gerência/liderança gerenciar ou desvincular canais de outros membros da organização.",
        badge: "Moderação",
      },
      {
        key: "force_end_live_session",
        label: "Encerrar Sessões de Live Manualmente",
        description: "Permite forçar o encerramento do status online de lives ativas na plataforma.",
        badge: "Operacional",
      },
      {
        key: "simulate_live_stream",
        label: "Simular Lives & Testar Notificações",
        description: "Permite disparar testes de simulação de abertura e encerramento de live para validar notificações sonoras e push.",
        badge: "Testes / Dev",
      },
      {
        key: "configure_stream_api",
        label: "Configurar Credenciais de APIs & Webhooks",
        description: "Permite configurar Client IDs, Secrets e tokens de conexão com Twitch, Kick, YouTube e TikTok.",
        badge: "Configuração API",
        importantNote: "Acesso a chaves confidenciais e credenciais de provedores de streaming.",
      },
      {
        key: "view_stream_logs",
        label: "Visualizar Histórico de Eventos & Logs de Stream",
        description: "Permite auditar o log detalhado de checagens periódicas, webhooks recebidos e alertas de início de live.",
        badge: "Logs / Auditoria",
      },
      {
        key: "manage_lives",
        label: "Gerenciamento Total do Módulo de Lives",
        description: "Concede autoridade completa sobre todas as ferramentas, contas de membros, webhooks e configurações de transmissão.",
        badge: "Super Gestão",
      },
    ],
  },
  {
    id: "estoque",
    title: "Estoque Geral e Depósitos",
    route: "/controledeestoque",
    icon: Boxes,
    description: "Visão geral, controle de insumos e gerenciamento de baús armazenados nos depósitos.",
    color: "border-sky-500/40 bg-sky-500/5 text-sky-400",
    defaultCat: "Gestão",
    defaultOrder: 3,
    permissions: [
      {
        key: "view_stock",
        label: "Ver Saldos do Estoque Geral",
        description: "Consultar as quantidades totais em estoque dos produtos da facção.",
      },
      {
        key: "view_baus",
        label: "Visualizar Lista de Baús",
        description: "Permite visualizar quais baús existem na facção e seus respectivos itens.",
      },
      {
        key: "manage_baus",
        label: "Criar, Editar e Excluir Baús",
        description: "Permite criar novos depósitos de armazenamento e alterar nomes de baús.",
        badge: "Gestão Baús",
      },
      {
        key: "view_products",
        label: "Ver Lista de Produtos Cadastrados",
        description: "Visualizar os insumos e itens disponíveis no catálogo.",
      },
      {
        key: "manage_products",
        label: "Cadastrar, Editar e Apagar Produtos",
        description: "Criar novos itens, alterar nomes, preços de custo e venda.",
        badge: "Catálogo",
      },
      {
        key: "view_categories",
        label: "Ver Categorias de Produtos",
        description: "Visualizar as categorias dos itens (Armas, Munições, Drogas, etc.).",
      },
      {
        key: "manage_categories",
        label: "Gerenciar Categorias de Produtos",
        description: "Criar, editar e excluir categorias de insumos.",
        badge: "Categorias",
      },
    ],
  },
  {
    id: "gestao-estoque",
    title: "Gestão de Estoque",
    route: "/gestao-estoque",
    icon: PackageCheck,
    description: "Gerenciamento completo do catálogo de produtos, categorias, baús de facção e controle de saldos de estoque.",
    color: "border-emerald-500/40 bg-emerald-500/5 text-emerald-400",
    defaultCat: "Gestão",
    defaultOrder: 4,
    permissions: [
      {
        key: "view_stock_management",
        label: "Acessar Gestão de Estoque",
        description: "Permite acessar a tela /gestao-estoque e visualizar as ferramentas administrativas de estoque.",
      },
      {
        key: "manage_stock_products",
        label: "Gerenciar Produtos (Criar / Editar / Apagar)",
        description: "Permite criar novos produtos no catálogo, alterar preços sugeridos, unidades, fotos e excluir itens.",
        badge: "Produtos",
      },
      {
        key: "manage_stock_categories",
        label: "Gerenciar Categorias (Criar / Editar / Apagar)",
        description: "Permite criar, renomear, redefinir descrições e apagar categorias de produtos da facção.",
        badge: "Categorias",
      },
      {
        key: "manage_stock_baus",
        label: "Gerenciar Baús da Facção (Criar / Editar / Apagar)",
        description: "Permite criar baús, configurar tipo de movimentação (automático via Discord / manual via painel) e excluir baús.",
        badge: "Baús",
      },
      {
        key: "adjust_stock_balance",
        label: "Lançar Ajustes de Saldo de Estoque",
        description: "Permite lançar acertos de contagem de inventário, créditos e débitos de produtos por baú com justificativa auditada.",
        badge: "Ajuste Saldo",
        importantNote: "Gera registros auditados não-removíveis no sistema.",
      },
      {
        key: "manage_stock_balance",
        label: "Gerenciar, Criar e Redefinir Saldos de Estoque",
        description: "Permite redefinir saldos absolutos de produtos ou zerar contagens de inventário em baús.",
        badge: "Ação Crítica",
        importantNote: "Altera o saldo patrimonial físico dos baús da organização.",
      },
    ],
  },
  {
    id: "membros",
    title: "Gerenciamento de Membros",
    route: "/membros",
    icon: Users,
    description: "Lista de integrantes da facção, aprovação de cadastros e alteração de cargos.",
    color: "border-purple-500/40 bg-purple-500/5 text-purple-400",
    defaultCat: "Gestão",
    defaultOrder: 4,
    permissions: [
      {
        key: "view_members",
        label: "Visualizar Lista de Membros",
        description: "Acessar a lista de integrantes do grupo com nomes, cargos, ID e telefone.",
      },
      {
        key: "view_sensitive_data",
        label: "Visualizar Dados Confidenciais e Sensurados dos Membros",
        description: "Permite visualizar IDs do Discord, estatísticas de presença e dados sensíveis completos dos membros sem censura.",
        badge: "Dados Confidenciais",
      },
      {
        key: "view_consolidated_financials",
        label: "Ver Dados Financeiros dos Membros",
        description: "Permite visualizar valores acumulados de vendas e contribuições por membro.",
      },
      {
        key: "approve_requests",
        label: "Aprovar / Recusar Solicitações de Novos Membros",
        description: "Permite aprovar novos cadastros de jogadores que entraram pelo Discord, ativando-os como Novatos, ou rejeitar solicitações.",
        badge: "Aprovação de Cadastros",
      },
      {
        key: "promote_members",
        label: "Promover / Alterar Cargo de Membros",
        description: "Permite promover ou rebaixar o cargo hierárquico de membros inferiores.",
        importantNote: "Regra Estrita: Só permite alterar cargos de ranks estritamente inferiores.",
      },
      {
        key: "change_roles",
        label: "Alterar Patente Hierárquica Direta",
        description: "Permite modificar diretamente a patente ou nível hierárquico de integrantes.",
        badge: "Hierarquia",
      },
      {
        key: "edit_members",
        label: "Editar Dados de Membros",
        description: "Permite alterar nome, apelido, telefone e ID do personagem de membros inferiores.",
      },
      {
        key: "delete_members",
        label: "Desligar / Excluir Membros",
        description: "Permite desativar ou excluir registros de membros da facção.",
        badge: "Ação Crítica",
      },
    ],
  },
  {
    id: "fundo-caixa",
    title: "Fundo de Caixa",
    route: "/fundo-caixa",
    icon: Landmark,
    description: "Gestão do caixa geral da facção com entradas, saídas, estornos e saldo automático.",
    color: "border-emerald-500/40 bg-emerald-500/5 text-emerald-400",
    defaultCat: "Gestão",
    defaultOrder: 5,
    permissions: [
      {
        key: "view_cash_fund",
        label: "Acessar Fundo de Caixa",
        description: "Permite visualizar o saldo em tempo real e o histórico de movimentações financeiras.",
      },
      {
        key: "manage_cash_fund",
        label: "Registrar Lançamentos de Caixa",
        description: "Permite efetuar entradas (+) e saídas (-) de dinheiro no fundo de caixa.",
      },
      {
        key: "reverse_cash_fund",
        label: "Estornar Lançamentos de Caixa",
        description: "Permite estornar movimentações incorretas do caixa geral.",
        badge: "Estorno Financeiro",
      },
      {
        key: "delete_cash_movement",
        label: "Apagar / Excluir Lançamentos de Caixa",
        description: "Permite excluir definitivamente um registro do histórico do fundo de caixa.",
        badge: "Ação Crítica",
      },
    ],
  },
  {
    id: "rankings",
    title: "Rankings",
    route: "/rankings",
    icon: Trophy,
    description: "Pódio dos membros que mais movimentam estoques e realizam vendas na facção.",
    color: "border-amber-500/40 bg-amber-500/5 text-amber-400",
    defaultCat: "Gestão",
    defaultOrder: 6,
    permissions: [
      {
        key: "view_rankings",
        label: "Ver Rankings da Facção",
        description: "Acessar o pódio de membros em destaque.",
      },
    ],
  },
  {
    id: "desempenho",
    title: "Desempenho & Produtividade",
    route: "/desempenho",
    icon: TrendingUp,
    description: "Estatísticas avançadas de produtividade individual, raio-x dos integrantes e relatórios executivos.",
    color: "border-amber-500/40 bg-amber-500/5 text-amber-400",
    defaultCat: "Gestão",
    defaultOrder: 7,
    permissions: [
      {
        key: "view_performance",
        label: "Ver Meu Desempenho Pessoal (/desempenho)",
        description: "Permite ao membro consultar sua própria ficha técnica de faturamento e produtividade.",
      },
      {
        key: "manage_performance",
        label: "Acessar Gestão Executiva de Desempenho (/dev.desempenho)",
        description: "Permite acessar o painel geral da liderança com faturamento consolidado e ranking da facção.",
        badge: "Gestão Executiva",
      },
      {
        key: "inspect_member_performance",
        label: "Inspecionar Raio-X & Histórico de Membros",
        description: "Permite abrir o modal de inspeção individual para examinar vendas recentes e estoque por operador.",
        badge: "Raio-X Membros",
      },
    ],
  },
  {
    id: "metas",
    title: "Metas",
    route: "/metas",
    icon: Target,
    description: "Definição e acompanhamento de metas operacionais e de produção da equipe.",
    color: "border-amber-500/40 bg-amber-500/5 text-amber-400",
    defaultCat: "Gestão",
    defaultOrder: 8,
    permissions: [
      {
        key: "view_goals",
        label: "Visualizar Metas Semanais & Minhas Entregas",
        description: "Acessar a rota /metas, acompanhar metas ativas e enviar comprovantes de entrega de meta com print.",
      },
      {
        key: "manage_goals",
        label: "Gerenciar Metas Semanais & Validar Comprovantes",
        description: "Criar e editar metas da família, definir alvos e aprovar ou recusar prints de entrega de metas dos membros.",
        badge: "Gestão Metas",
      },
    ],
  },
  {
    id: "ausencias",
    title: "Ausências & Licenças",
    route: "/ausencias",
    icon: CalendarOff,
    description: "Registro e acompanhamento de ausências com data de início, data de volta, justificativas e gráficos estatísticos.",
    color: "border-amber-500/40 bg-amber-500/5 text-amber-400",
    defaultCat: "Gestão",
    defaultOrder: 9,
    permissions: [
      {
        key: "view_absences",
        label: "Acessar Aba de Ausências",
        description: "Permite acessar a rota /ausencias. Membros sem permissão de gestão visualizam apenas suas próprias ausências e a contagem geral de ausentes.",
        badge: "Acesso à Rota",
      },
      {
        key: "request_absence",
        label: "Solicitar / Informar Ausência",
        description: "Permite ao membro cadastrar novos períodos de ausência informando data de início, data de volta e motivo.",
      },
      {
        key: "manage_absences",
        label: "Gerenciar e Aprovar Ausências de Membros",
        description: "Permite à liderança aprovar/rejeitar pedidos de ausência, adicionar parecer e gerenciar licenças de todos os membros.",
        badge: "Gestão / Aprovação",
      },
      {
        key: "view_all_absences",
        label: "Visualizar Gráficos e Ausências de Todos os Membros",
        description: "Permite visualizar a lista completa de ausências de todos os membros e o painel de gráficos estatísticos da facção.",
        badge: "Gráficos & Métricas",
      },
    ],
  },
  {
    id: "cargos",
    title: "Gerenciamento de Cargos",
    route: "/cargos",
    icon: ShieldCheck,
    description: "Criação de novos cargos personalizados, ordem hierárquica e reordenação de níveis.",
    color: "border-purple-500/40 bg-purple-500/5 text-purple-400",
    defaultCat: "Gestão",
    defaultOrder: 9,
    permissions: [
      {
        key: "manage_roles",
        label: "Gerenciar Cargos e Hierarquia",
        description: "Permite criar cargos, editar nomes, descrições e reordenar a hierarquia.",
        badge: "Administrativo",
      },
    ],
  },
  {
    id: "permissoes",
    title: "Permissões",
    route: "/permissoes",
    icon: Settings,
    description: "Matriz de gerenciamento de permissões e controle de acesso aos módulos para cada cargo.",
    color: "border-indigo-500/40 bg-indigo-500/5 text-indigo-400",
    defaultCat: "Gestão",
    defaultOrder: 10,
    permissions: [
      {
        key: "manage_permissions",
        label: "Gerenciar Permissões por Página",
        description: "Permite configurar e ativar permissões individuais de cada cargo em tempo real.",
        badge: "Admin Permissões",
        importantNote: "Apenas administradores devem possuir permissão de alterar matrizes de cargos.",
      },
    ],
  },
  {
    id: "avisos",
    title: "Enviar Avisos",
    route: "/avisos",
    icon: Megaphone,
    description: "Publicação de comunicados gerais em destaque para toda a facção com confirmação de leitura.",
    color: "border-purple-500/40 bg-purple-500/5 text-purple-400",
    defaultCat: "Gestão",
    defaultOrder: 11,
    permissions: [
      {
        key: "manage_announcements",
        label: "Publicar e Apagar Comunicados",
        description: "Criar comunicados em destaque na página inicial e remover comunicados antigos.",
      },
    ],
  },
  {
    id: "configuracoes",
    title: "Configurações da Plataforma",
    route: "/configuracoes",
    icon: Wrench,
    description: "Gerenciamento das configurações gerais da facção, timeout de inatividade e personalização do menu lateral.",
    color: "border-indigo-500/40 bg-indigo-500/5 text-indigo-400",
    defaultCat: "Gestão",
    defaultOrder: 14,
    permissions: [
      {
        key: "manage_platform_settings",
        label: "Gerenciar Aba Plataforma",
        description: "Permite alterar o nome da facção, descrição, timeout de inatividade e parâmetros gerais.",
        badge: "Configurações",
      },
      {
        key: "manage_menu_settings",
        label: "Gerenciar Aba Menu",
        description: "Permite reordenar o menu lateral, alterar visibilidade dos itens e vincular categorias.",
        badge: "Gestão Menu",
      },
      {
        key: "trigger_force_cache_purge",
        label: "Disparar Limpeza Global de Cache e Reload",
        description: "Permite emitir o comando de limpeza de cache e recarregamento automático nos navegadores de todos os membros.",
        badge: "Ação Global / Dev",
        importantNote: "Ação de impacto global imediato em todos os navegadores conectados.",
      },
    ],
  },
  {
    id: "atualizacoes",
    title: "Atualizações do Sistema",
    route: "/atualizacoes",
    icon: Sparkles,
    description: "Histórico completo de releases, notas de atualização, novidades e correções postadas pelos desenvolvedores.",
    color: "border-emerald-500/40 bg-emerald-500/5 text-emerald-400",
    defaultCat: "Gestão",
    defaultOrder: 15,
    permissions: [
      {
        key: "view_patch_notes",
        label: "Visualizar Atualizações e Patch Notes (/atualizacoes)",
        description: "Permite acessar a rota /atualizacoes e acompanhar o feed de notas de versão e melhorias do sistema.",
        badge: "Acesso à Rota",
      },
      {
        key: "manage_patch_notes",
        label: "Postar, Editar e Gerenciar Atualizações",
        description: "Permite criar novas notas de atualização, adicionar imagens, publicar ou remover releases do sistema.",
        badge: "Dev / Gestão",
      },
    ],
  },
  {
    id: "perfil",
    title: "Meu Perfil",
    route: "/perfil",
    icon: User,
    description: "Visualização e edição dos dados pessoais do integrante (nome, apelido, telefone e passaporte).",
    color: "border-sky-500/40 bg-sky-500/5 text-sky-400",
    defaultCat: "Gestão",
    defaultOrder: 16,
    permissions: [
      {
        key: "view_profile",
        label: "Acessar e Editar Meu Perfil",
        description: "Permite acessar a página de perfil pessoal e alterar dados em jogo.",
      },
    ],
  },
  {
    id: "tickets",
    title: "Tickets / Ouvidoria",
    route: "/tickets",
    icon: LifeBuoy,
    description: "Canal interno e privado de solicitações, denúncias, reembolsos e ouvidoria direta com a gerência.",
    color: "border-amber-500/40 bg-amber-500/5 text-amber-400",
    defaultCat: "Gestão",
    defaultOrder: 17,
    permissions: [
      {
        key: "view_tickets",
        label: "Acessar Módulo Tickets / Ouvidoria",
        description: "Permite acessar a página /tickets e visualizar seus próprios chamados.",
        badge: "Acesso Geral",
      },
      {
        key: "create_ticket",
        label: "Abrir Novos Tickets / Solicitações",
        description: "Permite criar novos chamados com categoria, assunto, prioridade e anexos.",
      },
      {
        key: "view_all_tickets",
        label: "Visualizar Tickets de Todos os Membros",
        description: "Permite que a liderança visualize os tickets de toda a facção (em vez de apenas os próprios).",
        badge: "Liderança / Gestão",
      },
      {
        key: "manage_tickets",
        label: "Gerenciar, Responder e Fechar Chamados",
        description: "Permite assumir atendimento, transferir responsável, postar notas internas privadas, alterar status, resolver, reabrir e fechar tickets.",
        badge: "Gerência / Moderação",
        importantNote: "Acesso a notas internas confidenciais e alteração de status operacional de tickets.",
      },
    ],
  },
  {
    id: "notificacoes",
    title: "Central de Notificações",
    route: "/notificacoes",
    icon: Bell,
    description: "Visualização de todas as notificações do membro, histórico, alertas e preferências pessoais de som.",
    color: "border-sky-500/40 bg-sky-500/5 text-sky-400",
    defaultCat: "Operação",
    defaultOrder: 18,
    permissions: [
      {
        key: "view_notifications",
        label: "Visualizar Notificações & Histórico",
        description: "Permite acessar a rota /notificacoes, ler notificações recebidas e consultar histórico.",
        badge: "Acesso Geral",
      },
      {
        key: "manage_notifications",
        label: "Gerenciar Próprias Notificações",
        description: "Permite marcar notificações como lidas, dispensar ou excluir da sua caixa de entrada.",
        badge: "Gestão",
      },
      {
        key: "send_notifications",
        label: "Emitir Avisos e Notificações Rápidas",
        description: "Permite enviar notificações manuais, avisos importantes e comunicados direcionados a outros integrantes.",
        badge: "Envio",
      },
      {
        key: "configure_notifications_sound",
        label: "Personalizar Som e Alertas Individuais",
        description: "Permite alternar sons, silenciar canais e configurar categorias de notificações personalizadas.",
        badge: "Preferências",
      },
    ],
  },
  {
    id: "ceo",
    title: "Painel Executivo CEO",
    route: "/ceo",
    icon: Crown,
    description: "Central de comando executivo da liderança: métricas operacionais, automações do Bot Discloud, WebHooks e saúde financeira.",
    color: "border-amber-500/40 bg-amber-500/5 text-amber-400",
    defaultCat: "CEO",
    defaultOrder: 0,
    permissions: [
      {
        key: "view_ceo",
        label: "Acessar Painel Executivo CEO (/ceo)",
        description: "Permite acessar a rota /ceo e visualizar os indicadores executivos, métricas de faturamento e membros ativos.",
        badge: "Acesso Geral CEO",
      },
      {
        key: "manage_ceo_bot",
        label: "Gerenciar Bot Discloud (/ceo/bot)",
        description: "Permite monitorar instâncias do bot, uso de CPU/RAM, servidores mútuos e reiniciar a aplicação.",
        badge: "Bot Discord",
      },
      {
        key: "manage_ceo_webhooks",
        label: "WebHook Discord & Transmissões (/ceo/webhooks)",
        description: "Permite gerenciar canais de webhook, testar integrações e disparar anúncios ricos diretamente no Discord.",
        badge: "Webhooks",
      },
      {
        key: "view_ceo_financials",
        label: "Fundo de Caixa & Finanças (/ceo/financas)",
        description: "Permite auditar o extrato consolidado de movimentações financeiras, entradas, saídas e balanço global.",
        badge: "Finanças Executivas",
      },
    ],
  },
  {
    id: "ceo-bot",
    title: "Gerenciar Bot Discord",
    route: "/ceo/bot",
    icon: Bot,
    description: "Configurações de ciclo de vida, perfil visual, status operacional e presença do bot no painel CEO.",
    color: "border-indigo-500/40 bg-indigo-500/5 text-indigo-400",
    defaultCat: "CEO",
    defaultOrder: 1,
    permissions: [
      {
        key: "manage_ceo_bot",
        label: "Acesso Geral à Página de Gerenciar Bot (/ceo/bot)",
        description: "Permite acessar a rota /ceo/bot e visualizar o painel do bot.",
        badge: "Acesso Base",
      },
      {
        key: "bot_send_message",
        label: "Enviar Mensagem",
        description: "Permite visualizar e utilizar a opção/botão de enviar mensagem pelo bot no Discord.",
        badge: "Mensagem / Chat",
      },
      {
        key: "bot_add_app",
        label: "Adicionar App",
        description: "Permite visualizar e utilizar o botão '+ Adicionar app' para gerar o link OAuth2 e convidar o bot para o servidor Discord.",
        badge: "Adicionar App",
      },
      {
        key: "bot_change_presence",
        label: "Mudar Presença do Bot",
        description: "Permite alterar a presença operacional do bot (On-line, Parado, Não Incomodar, Invisível).",
        badge: "Presença",
      },
      {
        key: "bot_change_status",
        label: "Mudar Status do Bot",
        description: "Permite definir a mensagem de status e o tipo de atividade exibidos no perfil do bot.",
        badge: "Status & Atividade",
      },
      {
        key: "bot_change_name",
        label: "Mudar Nome do Bot",
        description: "Permite alterar o nome de exibição do bot no Discord.",
        badge: "Identidade",
      },
      {
        key: "bot_change_avatar",
        label: "Mudar Avatar do Bot",
        description: "Permite fazer upload, recortar e definir uma nova foto de perfil para o bot.",
        badge: "Visual / Avatar",
      },
      {
        key: "bot_change_banner",
        label: "Mudar Banner do Bot",
        description: "Permite carregar imagem personalizada ou selecionar presets para o banner do bot.",
        badge: "Visual / Banner",
      },
      {
        key: "bot_manage_roles",
        label: "Adicionar e Gerenciar Cargos do Bot",
        description: "Permite adicionar novos cargos visuais, escolher cores personalizadas, editar e remover cargos atribuídos ao perfil do bot.",
        badge: "Cargos / Perfil",
      },
      {
        key: "bot_restart",
        label: "Reiniciar Bot",
        description: "Permite emitir o comando para reiniciar a aplicação do bot.",
        badge: "Ciclo de Vida",
      },
      {
        key: "bot_power_toggle",
        label: "Ligar / Desligar Bot",
        description: "Permite iniciar ou parar a instância do bot.",
        badge: "Ciclo de Vida",
      },
      {
        key: "bot_invite",
        label: "Link de Convite OAuth2",
        description: "Permite gerar e acessar o link direto de convite com permissões de administrador para o bot.",
        badge: "Convite OAuth2",
      },
      {
        key: "bot_manage_token",
        label: "Visualizar & Gerenciar Token do Bot",
        description: "Permite visualizar credenciais e atualizar a chave/token da aplicação Discord.",
        badge: "Credenciais / Token",
      },
      {
        key: "bot_view_intents",
        label: "Visualizar Gateway Intents",
        description: "Permite inspecionar as Privileged Gateway Intents do bot (Presence, Server Members, Message Content).",
        badge: "Intents",
      },
      {
        key: "bot_change_intents",
        label: "Alterar Gateway Intents",
        description: "Permite ativar ou desativar permissões de intents privilegiados da aplicação.",
        badge: "Intents",
      },
      {
        key: "bot_manage_discloud_config",
        label: "Configurações Discloud (discloud.config)",
        description: "Permite inspecionar e alterar parâmetros de memória RAM, versão do Node e tipo de build no Discloud.",
        badge: "Discloud Config",
      },
    ],
  },
  {
    id: "ceo-webhooks",
    title: "WebHook Discord & Transmissões",
    route: "/ceo/webhooks",
    icon: Webhook,
    description: "Gerenciamento de canais de webhooks, envio de transmissões ricas (embeds), testes, edição e integração com Discord.",
    color: "border-violet-500/40 bg-violet-500/5 text-violet-400",
    defaultCat: "CEO",
    defaultOrder: 2,
    permissions: [
      {
        key: "manage_ceo_webhooks",
        label: "Acesso Geral à Página WebHook Discord (/ceo/webhooks)",
        description: "Permite acessar a rota /ceo/webhooks e visualizar a listagem de canais e webhooks configurados.",
        badge: "Acesso Base",
      },
      {
        key: "webhook_send_message",
        label: "Disparar Mensagens & Anúncios Embed",
        description: "Permite abrir o modal de transmissão e enviar mensagens ricas com imagem, menções e formatação embed para os canais do Discord.",
        badge: "Disparo de Mensagens",
      },
      {
        key: "webhook_test",
        label: "Testar Envio no Canal do Discord",
        description: "Permite executar o teste rápido de conexão enviando uma notificação de verificação ao webhook.",
        badge: "Teste de Conexão",
      },
      {
        key: "webhook_create",
        label: "Criar / Adicionar Novos Webhooks",
        description: "Permite cadastrar novos canais de webhook, configurar URLs do Discord, avatar e presets de servidor.",
        badge: "Criação",
      },
      {
        key: "webhook_edit",
        label: "Editar Configurações de Webhooks",
        description: "Permite alterar nome, apelido, avatar, thumbnail, banner e canal de webhooks existentes.",
        badge: "Edição",
      },
      {
        key: "webhook_delete",
        label: "Excluir Webhooks do Sistema",
        description: "Permite remover permanentemente webhooks e canais cadastrados da lista.",
        badge: "Exclusão",
      },
      {
        key: "webhook_toggle_active",
        label: "Ativar / Pausar Webhook",
        description: "Permite alternar o status operacional do webhook (ativado ou em pausa).",
        badge: "Status Operacional",
      },
      {
        key: "webhook_copy_url",
        label: "Copiar Link Oficial do Webhook",
        description: "Permite copiar a URL oficial do webhook compatível com Discohook, FiveM e scripts externos.",
        badge: "Compartilhamento",
      },
      {
        key: "webhook_view_code",
        label: "Visualizar Códigos de Integração",
        description: "Permite abrir o modal 'Como Usar' e inspecionar os snippets de integração em cURL, JavaScript e Python.",
        badge: "Integração / Dev",
      },
      {
        key: "webhook_save_config",
        label: "Salvar Configurações Globais",
        description: "Permite salvar alterações globais da lista de webhooks e persistir no banco de dados.",
        badge: "Persistência",
      },
    ],
  },
  {
    id: "ceo-financas",
    title: "Fundo de Caixa & Finanças Executivas",
    route: "/ceo/financas",
    icon: Landmark,
    description: "Auditoria contábil completa: extrato unificado de entradas e saídas, faturamento acumulado e saldo geral do cofre.",
    color: "border-emerald-500/40 bg-emerald-500/5 text-emerald-400",
    defaultCat: "CEO",
    defaultOrder: 3,
    permissions: [
      {
        key: "view_ceo_financials",
        label: "Acesso Geral ao Módulo de Finanças (/ceo/financas)",
        description: "Permite acessar a rota /ceo/financas e auditar os relatórios financeiros consolidados.",
        badge: "Acesso Base",
      },
      {
        key: "view_cash_fund",
        label: "Visualizar Saldo & Histórico do Fundo de Caixa",
        description: "Permite visualizar o saldo monetário corrente e o histórico de aportes e retiradas.",
        badge: "Fundo de Caixa",
      },
      {
        key: "view_consolidated_financials",
        label: "Visualizar Balanço Consolidado da Facção",
        description: "Permite acompanhar gráficos analíticos de fluxo de caixa, comissões de membros e receita líquida.",
        badge: "Consolidado",
      },
    ],
  },
  {
    id: "dev-hub",
    title: "Hub do Desenvolvedor",
    route: "/dev",
    icon: Code2,
    description: "Central principal de ferramentas do sistema: monitoramento do servidor, status de APIs e atalhos rápidos de desenvolvimento.",
    color: "border-rose-500/40 bg-rose-500/5 text-rose-400",
    defaultCat: "DEV",
    defaultOrder: 0,
    permissions: [
      {
        key: "view_dev_hub",
        label: "Acesso ao Hub Desenvolvedor (/dev)",
        description: "Permite acessar a rota /dev e visualizar o dashboard central de engenharia e ferramentas de infraestrutura.",
        badge: "Acesso Geral Dev",
      },
    ],
  },
  {
    id: "dev-bot",
    title: "Gerenciador do Bot Discloud (Dev)",
    route: "/dev/bot",
    icon: Bot,
    description: "Terminal avançado do bot: controle de processos em tempo real, consumo de memória, console de logs e integração Discloud.",
    color: "border-indigo-500/40 bg-indigo-500/5 text-indigo-400",
    defaultCat: "DEV",
    defaultOrder: 1,
    permissions: [
      {
        key: "manage_dev_bot",
        label: "Acesso ao Gerenciador de Bot Dev (/dev/bot)",
        description: "Permite acessar o console avançado de infraestrutura do bot no Discloud, visualizar logs de terminal e reiniciar.",
        badge: "Infraestrutura Bot",
      },
      {
        key: "bot_manage_discloud_config",
        label: "Gerenciar Arquivo discloud.config & Parâmetros de Hospedagem",
        description: "Permite inspecionar parâmetros da VM, alocação de RAM e arquivo de configuração do bot.",
        badge: "Discloud Config",
      },
    ],
  },
  {
    id: "dev-patch-notes",
    title: "Publicação de Patch Notes (Dev)",
    route: "/dev/patch-notes",
    icon: ScrollText,
    description: "Editor de releases do sistema: criação, formatação e publicação de notas de versão para todos os integrantes.",
    color: "border-amber-500/40 bg-amber-500/5 text-amber-400",
    defaultCat: "DEV",
    defaultOrder: 2,
    permissions: [
      {
        key: "manage_dev_patch_notes",
        label: "Publicar e Editar Notas de Atualização (/dev/patch-notes)",
        description: "Permite criar novas versões, cadastrar changelogs, correções e novidades que aparecem na tela de Patch Notes.",
        badge: "Editor de Releases",
      },
      {
        key: "manage_patch_notes",
        label: "Gerenciar Histórico de Atualizações",
        description: "Permite excluir, republicar ou alterar visibilidade de notas de versão anteriores.",
        badge: "Gestão de Histórico",
      },
    ],
  },
  {
    id: "dev-desempenho",
    title: "Diagnóstico & Desempenho (Dev)",
    route: "/dev/desempenho",
    icon: TrendingUp,
    description: "Painel de métricas de saúde: latência do Supabase, medição de renderização da interface e limpeza forçada de caches.",
    color: "border-emerald-500/40 bg-emerald-500/5 text-emerald-400",
    defaultCat: "DEV",
    defaultOrder: 3,
    permissions: [
      {
        key: "manage_dev_performance",
        label: "Acesso ao Painel de Desempenho (/dev/desempenho)",
        description: "Permite monitorar tempos de resposta de consultas, health checks de banco de dados e estado dos serviços.",
        badge: "Métricas & Saúde",
      },
      {
        key: "trigger_force_cache_purge",
        label: "Disparar Purge Global de Cache dos Navegadores",
        description: "Emite comando em tempo real para todos os clientes conectados limparem Service Workers e recarregarem a aplicação.",
        badge: "Comando Crítico",
        importantNote: "Afeta imediatamente todos os membros ativos na aplicação.",
      },
    ],
  },
  {
    id: "dev-permissoes",
    title: "Permissões Avançadas & Tags (Dev)",
    route: "/dev/permissoes",
    icon: ShieldCheck,
    description: "Matriz global de controle de acesso: configuração de privilégios das Tags Desenvolvedor e CEO, e atribuição de membros.",
    color: "border-rose-500/40 bg-rose-500/5 text-rose-400",
    defaultCat: "DEV",
    defaultOrder: 4,
    permissions: [
      {
        key: "manage_dev_permissions",
        label: "Acesso ao Controle de Permissões Dev (/dev/permissoes)",
        description: "Permite gerenciar a matriz de permissões das Tags Desenvolvedor e CEO e alternar membros com a tag ativa.",
        badge: "Controle de Acesso",
      },
      {
        key: "manage_permissions",
        label: "Gerenciar Permissões por Cargo no Sistema",
        description: "Permite editar privilégios de cargos padrão da hierarquia (01, 02, Gerente, Motoqueiro, etc.).",
        badge: "Cargos & Matriz",
      },
    ],
  },
  {
    id: "dev-configuracao",
    title: "Configurações Globais do Sistema (Dev)",
    route: "/dev/configuracao",
    icon: Settings,
    description: "Ajustes de baixo nível da plataforma: flags de ambiente, bypass de autorização, parâmetros de auditoria e banco de dados.",
    color: "border-sky-500/40 bg-sky-500/5 text-sky-400",
    defaultCat: "DEV",
    defaultOrder: 5,
    permissions: [
      {
        key: "manage_dev_config",
        label: "Acesso às Configurações Globais Dev (/dev/configuracao)",
        description: "Permite configurar flags técnicas do sistema, alternar ambiente de homologação e inspecionar variáveis.",
        badge: "Configurações Core",
      },
      {
        key: "manage_platform_settings",
        label: "Salvar Parâmetros Globais da Plataforma",
        description: "Permite persistir configurações na tabela platform_settings e atualizar o comportamento operacional do painel.",
        badge: "Persistência Global",
      },
    ],
  },
  {
    id: "dev-menu-lateral",
    title: "Personalização do Menu Lateral (Dev)",
    route: "/dev/menu-lateral",
    icon: Wrench,
    description: "Gerenciador da barra de navegação: reordenação de rotas, definição de ícones, criação de categorias e controle de exibição.",
    color: "border-purple-500/40 bg-purple-500/5 text-purple-400",
    defaultCat: "DEV",
    defaultOrder: 6,
    permissions: [
      {
        key: "manage_dev_menu",
        label: "Acesso ao Gerenciador de Menu Lateral (/dev/menu-lateral)",
        description: "Permite personalizar a estrutura visual e posições de todos os itens do menu lateral da aplicação.",
        badge: "Menu Lateral",
      },
      {
        key: "manage_menu_settings",
        label: "Salvar Estrutura do Menu para Toda a Facção",
        description: "Permite salvar configurações de menus que se aplicam a todos os integrantes e cargos da organização.",
        badge: "Persistência de Menus",
      },
    ],
  },
  {
    id: "ceo-notificacoes",
    title: "Central de Notificações (CEO)",
    route: "/ceo/notificacoes",
    icon: Crown,
    description: "Comando executivo de notificações: envio de comunicados para toda a facção ou cargos específicos, edição e controle ativo.",
    color: "border-amber-500/40 bg-amber-500/5 text-amber-400",
    defaultCat: "CEO",
    defaultOrder: 4,
    permissions: [
      {
        key: "view_ceo_notifications",
        label: "Acesso à Central de Notificações CEO (/ceo/notificacoes)",
        description: "Permite acessar o dashboard executivo de gerenciamento de notificações da diretoria.",
        badge: "Acesso Executivo",
      },
      {
        key: "create_ceo_notification",
        label: "Criar & Disparar Notificações Broadcast",
        description: "Permite emitir comunicados para toda a organização ou direcionados a patentes selecionadas.",
        badge: "Broadcast",
      },
      {
        key: "edit_ceo_notification",
        label: "Editar Notificações Ativas",
        description: "Permite alterar o conteúdo, categoria ou link de notificações em andamento.",
        badge: "Edição",
      },
      {
        key: "toggle_ceo_notification_active",
        label: "Ativar / Pausar Notificações",
        description: "Permite pausar ou reativar notificações do sistema da facção.",
        badge: "Controle de Status",
      },
      {
        key: "delete_ceo_notification",
        label: "Excluir Notificações Globais",
        description: "Permite remover notificações ativas do painel de todos os integrantes.",
        badge: "Exclusão",
      },
    ],
  },
  {
    id: "dev-notificacoes",
    title: "Central de Notificações & Regras (Dev)",
    route: "/dev/notificacoes",
    icon: BellRing,
    description: "Gestão técnica de telemetria, simulador em tempo real e matriz de regras de permissão de notificações por cargo e tag.",
    color: "border-rose-500/40 bg-rose-500/5 text-rose-400",
    defaultCat: "DEV",
    defaultOrder: 7,
    permissions: [
      {
        key: "view_dev_notifications",
        label: "Acesso à Central de Notificações Dev (/dev/notificacoes)",
        description: "Permite acessar o console avançado de engenharia de notificações, logs e telemetria.",
        badge: "Acesso Geral Dev",
      },
      {
        key: "manage_dev_notification_rules",
        label: "Gerenciar Regras de Notificação por Cargo e Tag",
        description: "Permite configurar quais tipos de notificações chegam a cada patente e tag da organização.",
        badge: "Matriz de Regras",
      },
      {
        key: "create_dev_notification",
        label: "Criar Notificações com Metadados Técnicos",
        description: "Permite emitir notificações com parâmetros avançados de áudio, deep-link e prioridades.",
        badge: "Disparo Dev",
      },
      {
        key: "edit_dev_notification",
        label: "Editar Qualquer Notificação do Sistema",
        description: "Permite modificar qualquer notificação persistida no banco de dados sem restrições.",
        badge: "Edição Irrestrita",
      },
      {
        key: "delete_dev_notification",
        label: "Apagar & Purgar Histórico em Massa",
        description: "Permite excluir qualquer notificação e executar limpeza forçada do banco.",
        badge: "Purga Dev",
      },
      {
        key: "simulate_dev_notification",
        label: "Simulador de Disparos em Tempo Real",
        description: "Permite simular eventos de notificação com som e validação imediata na interface.",
        badge: "Simulador",
      },
      {
        key: "toggle_dev_notification_active",
        label: "Ativar / Pausar Notificações no Sistema",
        description: "Permite pausar a exibição ou reativar notificações sem removê-las do banco.",
        badge: "Controle de Ativação",
      },
      {
        key: "purge_dev_notifications",
        label: "Expurgo em Massa de Notificações",
        description: "Permite executar purga filtrada por tipo, categoria ou idade em dias.",
        badge: "Limpeza & Purga",
      },
      {
        key: "inspect_dev_notification_payload",
        label: "Inspecionar Payload JSON e Metadados Técnicos",
        description: "Permite visualizar estrutura completa de dados em JSON, read_by e metadados.",
        badge: "Inspeção Dev",
      },
      {
        key: "export_dev_notifications",
        label: "Exportar Histórico e Logs em JSON",
        description: "Permite download e exportação de relatórios de telemetria e notificações.",
        badge: "Exportação",
      },
      {
        key: "manage_dev_notification_sounds",
        label: "Configurar e Testar Alertas Sonoros Dev",
        description: "Permite testar disparos acústicos e sincronizar áudios de notificação.",
        badge: "Áudio & Som",
      },
      {
        key: "broadcast_dev_emergency_alert",
        label: "Disparo de Alerta de Emergência Global",
        description: "Permite emitir broadcast de alerta crítico com banner e prioridade máxima.",
        badge: "Alerta Crítico",
      },
    ],
  },
  {
    id: "dev-estoque",
    title: "Ajustes de Estoque & Integração Discord (Dev)",
    route: "/dev/estoque",
    icon: Boxes,
    description: "Configurações do canal de logs do Discord, telemetria em tempo real, auditoria técnica e realização exclusiva de ajustes manuais de estoque.",
    color: "border-emerald-500/40 bg-emerald-500/5 text-emerald-400",
    defaultCat: "DEV",
    defaultOrder: 8,
    permissions: [
      {
        key: "estoque.visualizar",
        label: "Visualizar Painel de Controle de Estoque Dev",
        description: "Permite acessar o console de estoque dev, ver inventários e status da conexão com Discord.",
        badge: "Acesso Estoque Dev",
      },
      {
        key: "estoque.ajustar",
        label: "Ajustar Saldo de Estoque",
        description: "Permite executar ajustes de saldo em baús automáticos e manuais com auditoria obrigatória.",
        badge: "Ajustes Manuais",
      },
      {
        key: "estoque.adicionar",
        label: "Adicionar Itens ao Estoque",
        description: "Permite lançar acréscimos (+) de insumos e itens diretamente nos depósitos.",
        badge: "Entrada Dev",
      },
      {
        key: "estoque.remover",
        label: "Remover Itens do Estoque",
        description: "Permite dar baixa (-) em quantidades de itens nos depósitos através do console.",
        badge: "Saída Dev",
      },
      {
        key: "estoque.corrigir",
        label: "Corrigir e Definir Saldo Específico",
        description: "Permite definir o saldo exato de um item no baú (ex: zerar ou recalibrar quantidade).",
        badge: "Correção Exata",
      },
      {
        key: "estoque.configurar",
        label: "Configurar Parâmetros e Mapeamento Discord",
        description: "Permite alterar Servidor, Canal de logs, ativar/desativar motor e gerenciar mapeamento de itens.",
        badge: "Configuração Discord",
      },
      {
        key: "estoque.auditoria",
        label: "Auditoria Técnica e Logs de Movimentação",
        description: "Permite visualizar histórico completo de mensagens do Discord, logs processadas e rejeitadas.",
        badge: "Auditoria",
      },
    ],
  },
];
