/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAvisosRouteImport } from './routes/_authenticated/avisos'
import { Route as AuthenticatedBausRouteImport } from './routes/_authenticated/baus'
import { Route as AuthenticatedCargosRouteImport } from './routes/_authenticated/cargos'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDesempenhoRouteImport } from './routes/_authenticated/desempenho'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedFundoCaixaRouteImport } from './routes/_authenticated/fundo-caixa'
import { Route as AuthenticatedHierarquiaRouteImport } from './routes/_authenticated/hierarquia'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedMembrosRouteImport } from './routes/_authenticated/membros'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedMovimentacoesRouteImport } from './routes/_authenticated/movimentacoes'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPermissoesRouteImport } from './routes/_authenticated/permissoes'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedRankingsRouteImport } from './routes/_authenticated/rankings'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DevDiscordIdRouteImport } from './routes/dev.$discordId'
import { Route as AuthenticatedDevIndexRouteImport } from './routes/_authenticated/dev.index'
import { Route as AuthenticatedDevConfiguracaoRouteImport } from './routes/_authenticated/dev.configuracao'
import { Route as AuthenticatedDevDesempenhoRouteImport } from './routes/_authenticated/dev.desempenho'
import { Route as AuthenticatedDevMenuLateralRouteImport } from './routes/_authenticated/dev.menu-lateral'
import { Route as AuthenticatedDevPermissoesRouteImport } from './routes/_authenticated/dev.permissoes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAvisosRoute = AuthenticatedAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBausRoute = AuthenticatedBausRouteImport.update({
  id: '/baus',
  path: '/baus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCargosRoute = AuthenticatedCargosRouteImport.update({
  id: '/cargos',
  path: '/cargos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesempenhoRoute = AuthenticatedDesempenhoRouteImport.update({
  id: '/desempenho',
  path: '/desempenho',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFundoCaixaRoute = AuthenticatedFundoCaixaRouteImport.update({
  id: '/fundo-caixa',
  path: '/fundo-caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHierarquiaRoute = AuthenticatedHierarquiaRouteImport.update({
  id: '/hierarquia',
  path: '/hierarquia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembrosRoute = AuthenticatedMembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovimentacoesRoute =
  AuthenticatedMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissoesRoute = AuthenticatedPermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingsRoute = AuthenticatedRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDiscordIdRoute = DevDiscordIdRouteImport.update({
  id: '/dev/$discordId',
  path: '/dev/$discordId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDevIndexRoute = AuthenticatedDevIndexRouteImport.update({
  id: '/dev/',
  path: '/dev/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevConfiguracaoRoute =
  AuthenticatedDevConfiguracaoRouteImport.update({
    id: '/dev/configuracao',
    path: '/dev/configuracao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevDesempenhoRoute =
  AuthenticatedDevDesempenhoRouteImport.update({
    id: '/dev/desempenho',
    path: '/dev/desempenho',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevMenuLateralRoute =
  AuthenticatedDevMenuLateralRouteImport.update({
    id: '/dev/menu-lateral',
    path: '/dev/menu-lateral',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevPermissoesRoute =
  AuthenticatedDevPermissoesRouteImport.update({
    id: '/dev/permissoes',
    path: '/dev/permissoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/baus': typeof AuthenticatedBausRoute
  '/cargos': typeof AuthenticatedCargosRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/chat': typeof AuthenticatedChatRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/desempenho': typeof AuthenticatedDesempenhoRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/fundo-caixa': typeof AuthenticatedFundoCaixaRoute
  '/hierarquia': typeof AuthenticatedHierarquiaRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/membros': typeof AuthenticatedMembrosRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/permissoes': typeof AuthenticatedPermissoesRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/rankings': typeof AuthenticatedRankingsRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev/$discordId': typeof DevDiscordIdRoute
  '/dev/configuracao': typeof AuthenticatedDevConfiguracaoRoute
  '/dev/desempenho': typeof AuthenticatedDevDesempenhoRoute
  '/dev/menu-lateral': typeof AuthenticatedDevMenuLateralRoute
  '/dev/permissoes': typeof AuthenticatedDevPermissoesRoute
  '/dev/': typeof AuthenticatedDevIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/avisos': typeof AuthenticatedAvisosRoute
  '/baus': typeof AuthenticatedBausRoute
  '/cargos': typeof AuthenticatedCargosRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/chat': typeof AuthenticatedChatRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/desempenho': typeof AuthenticatedDesempenhoRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/fundo-caixa': typeof AuthenticatedFundoCaixaRoute
  '/hierarquia': typeof AuthenticatedHierarquiaRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/membros': typeof AuthenticatedMembrosRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/permissoes': typeof AuthenticatedPermissoesRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/rankings': typeof AuthenticatedRankingsRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev/$discordId': typeof DevDiscordIdRoute
  '/dev/configuracao': typeof AuthenticatedDevConfiguracaoRoute
  '/dev/desempenho': typeof AuthenticatedDevDesempenhoRoute
  '/dev/menu-lateral': typeof AuthenticatedDevMenuLateralRoute
  '/dev/permissoes': typeof AuthenticatedDevPermissoesRoute
  '/dev': typeof AuthenticatedDevIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/avisos': typeof AuthenticatedAvisosRoute
  '/_authenticated/baus': typeof AuthenticatedBausRoute
  '/_authenticated/cargos': typeof AuthenticatedCargosRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/desempenho': typeof AuthenticatedDesempenhoRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/fundo-caixa': typeof AuthenticatedFundoCaixaRoute
  '/_authenticated/hierarquia': typeof AuthenticatedHierarquiaRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/membros': typeof AuthenticatedMembrosRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/movimentacoes': typeof AuthenticatedMovimentacoesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/permissoes': typeof AuthenticatedPermissoesRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/rankings': typeof AuthenticatedRankingsRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev/$discordId': typeof DevDiscordIdRoute
  '/_authenticated/dev/configuracao': typeof AuthenticatedDevConfiguracaoRoute
  '/_authenticated/dev/desempenho': typeof AuthenticatedDevDesempenhoRoute
  '/_authenticated/dev/menu-lateral': typeof AuthenticatedDevMenuLateralRoute
  '/_authenticated/dev/permissoes': typeof AuthenticatedDevPermissoesRoute
  '/_authenticated/dev/': typeof AuthenticatedDevIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/avisos'
    | '/baus'
    | '/cargos'
    | '/categorias'
    | '/chat'
    | '/configuracoes'
    | '/dashboard'
    | '/desempenho'
    | '/estoque'
    | '/fundo-caixa'
    | '/hierarquia'
    | '/logs'
    | '/membros'
    | '/metas'
    | '/movimentacoes'
    | '/perfil'
    | '/permissoes'
    | '/produtos'
    | '/rankings'
    | '/vendas'
    | '/auth/callback'
    | '/dev/$discordId'
    | '/dev/configuracao'
    | '/dev/desempenho'
    | '/dev/menu-lateral'
    | '/dev/permissoes'
    | '/dev/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/avisos'
    | '/baus'
    | '/cargos'
    | '/categorias'
    | '/chat'
    | '/configuracoes'
    | '/dashboard'
    | '/desempenho'
    | '/estoque'
    | '/fundo-caixa'
    | '/hierarquia'
    | '/logs'
    | '/membros'
    | '/metas'
    | '/movimentacoes'
    | '/perfil'
    | '/permissoes'
    | '/produtos'
    | '/rankings'
    | '/vendas'
    | '/auth/callback'
    | '/dev/$discordId'
    | '/dev/configuracao'
    | '/dev/desempenho'
    | '/dev/menu-lateral'
    | '/dev/permissoes'
    | '/dev'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/avisos'
    | '/_authenticated/baus'
    | '/_authenticated/cargos'
    | '/_authenticated/categorias'
    | '/_authenticated/chat'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/desempenho'
    | '/_authenticated/estoque'
    | '/_authenticated/fundo-caixa'
    | '/_authenticated/hierarquia'
    | '/_authenticated/logs'
    | '/_authenticated/membros'
    | '/_authenticated/metas'
    | '/_authenticated/movimentacoes'
    | '/_authenticated/perfil'
    | '/_authenticated/permissoes'
    | '/_authenticated/produtos'
    | '/_authenticated/rankings'
    | '/_authenticated/vendas'
    | '/auth/callback'
    | '/dev/$discordId'
    | '/_authenticated/dev/configuracao'
    | '/_authenticated/dev/desempenho'
    | '/_authenticated/dev/menu-lateral'
    | '/_authenticated/dev/permissoes'
    | '/_authenticated/dev/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  DevDiscordIdRoute: typeof DevDiscordIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/avisos': {
      id: '/_authenticated/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AuthenticatedAvisosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/baus': {
      id: '/_authenticated/baus'
      path: '/baus'
      fullPath: '/baus'
      preLoaderRoute: typeof AuthenticatedBausRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cargos': {
      id: '/_authenticated/cargos'
      path: '/cargos'
      fullPath: '/cargos'
      preLoaderRoute: typeof AuthenticatedCargosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desempenho': {
      id: '/_authenticated/desempenho'
      path: '/desempenho'
      fullPath: '/desempenho'
      preLoaderRoute: typeof AuthenticatedDesempenhoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fundo-caixa': {
      id: '/_authenticated/fundo-caixa'
      path: '/fundo-caixa'
      fullPath: '/fundo-caixa'
      preLoaderRoute: typeof AuthenticatedFundoCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hierarquia': {
      id: '/_authenticated/hierarquia'
      path: '/hierarquia'
      fullPath: '/hierarquia'
      preLoaderRoute: typeof AuthenticatedHierarquiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/membros': {
      id: '/_authenticated/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof AuthenticatedMembrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimentacoes': {
      id: '/_authenticated/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AuthenticatedMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissoes': {
      id: '/_authenticated/permissoes'
      path: '/permissoes'
      fullPath: '/permissoes'
      preLoaderRoute: typeof AuthenticatedPermissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rankings': {
      id: '/_authenticated/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof AuthenticatedRankingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/$discordId': {
      id: '/dev/$discordId'
      path: '/dev/$discordId'
      fullPath: '/dev/$discordId'
      preLoaderRoute: typeof DevDiscordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dev/': {
      id: '/_authenticated/dev/'
      path: '/dev'
      fullPath: '/dev/'
      preLoaderRoute: typeof AuthenticatedDevIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev/configuracao': {
      id: '/_authenticated/dev/configuracao'
      path: '/dev/configuracao'
      fullPath: '/dev/configuracao'
      preLoaderRoute: typeof AuthenticatedDevConfiguracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev/desempenho': {
      id: '/_authenticated/dev/desempenho'
      path: '/dev/desempenho'
      fullPath: '/dev/desempenho'
      preLoaderRoute: typeof AuthenticatedDevDesempenhoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev/menu-lateral': {
      id: '/_authenticated/dev/menu-lateral'
      path: '/dev/menu-lateral'
      fullPath: '/dev/menu-lateral'
      preLoaderRoute: typeof AuthenticatedDevMenuLateralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev/permissoes': {
      id: '/_authenticated/dev/permissoes'
      path: '/dev/permissoes'
      fullPath: '/dev/permissoes'
      preLoaderRoute: typeof AuthenticatedDevPermissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAvisosRoute: typeof AuthenticatedAvisosRoute
  AuthenticatedBausRoute: typeof AuthenticatedBausRoute
  AuthenticatedCargosRoute: typeof AuthenticatedCargosRoute
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDesempenhoRoute: typeof AuthenticatedDesempenhoRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedFundoCaixaRoute: typeof AuthenticatedFundoCaixaRoute
  AuthenticatedHierarquiaRoute: typeof AuthenticatedHierarquiaRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedMembrosRoute: typeof AuthenticatedMembrosRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedMovimentacoesRoute: typeof AuthenticatedMovimentacoesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPermissoesRoute: typeof AuthenticatedPermissoesRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedRankingsRoute: typeof AuthenticatedRankingsRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedDevConfiguracaoRoute: typeof AuthenticatedDevConfiguracaoRoute
  AuthenticatedDevDesempenhoRoute: typeof AuthenticatedDevDesempenhoRoute
  AuthenticatedDevMenuLateralRoute: typeof AuthenticatedDevMenuLateralRoute
  AuthenticatedDevPermissoesRoute: typeof AuthenticatedDevPermissoesRoute
  AuthenticatedDevIndexRoute: typeof AuthenticatedDevIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAvisosRoute: AuthenticatedAvisosRoute,
  AuthenticatedBausRoute: AuthenticatedBausRoute,
  AuthenticatedCargosRoute: AuthenticatedCargosRoute,
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDesempenhoRoute: AuthenticatedDesempenhoRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedFundoCaixaRoute: AuthenticatedFundoCaixaRoute,
  AuthenticatedHierarquiaRoute: AuthenticatedHierarquiaRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedMembrosRoute: AuthenticatedMembrosRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedMovimentacoesRoute: AuthenticatedMovimentacoesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPermissoesRoute: AuthenticatedPermissoesRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedRankingsRoute: AuthenticatedRankingsRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedDevConfiguracaoRoute: AuthenticatedDevConfiguracaoRoute,
  AuthenticatedDevDesempenhoRoute: AuthenticatedDevDesempenhoRoute,
  AuthenticatedDevMenuLateralRoute: AuthenticatedDevMenuLateralRoute,
  AuthenticatedDevPermissoesRoute: AuthenticatedDevPermissoesRoute,
  AuthenticatedDevIndexRoute: AuthenticatedDevIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  DevDiscordIdRoute: DevDiscordIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
