/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HandleRouteImport } from './routes/$handle'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedAtualizacoesRouteImport } from './routes/_authenticated/atualizacoes'
import { Route as AuthenticatedAusenciasRouteImport } from './routes/_authenticated/ausencias'
import { Route as AuthenticatedAvisosRouteImport } from './routes/_authenticated/avisos'
import { Route as AuthenticatedBausRouteImport } from './routes/_authenticated/baus'
import { Route as AuthenticatedCargosRouteImport } from './routes/_authenticated/cargos'
import { Route as AuthenticatedCategoriasRouteImport } from './routes/_authenticated/categorias'
import { Route as AuthenticatedCeoRouteImport } from './routes/_authenticated/ceo'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDesempenhoRouteImport } from './routes/_authenticated/desempenho'
import { Route as AuthenticatedEstoqueRouteImport } from './routes/_authenticated/estoque'
import { Route as AuthenticatedFundoCaixaRouteImport } from './routes/_authenticated/fundo-caixa'
import { Route as AuthenticatedHierarquiaRouteImport } from './routes/_authenticated/hierarquia'
import { Route as AuthenticatedLivesRouteImport } from './routes/_authenticated/lives'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedMembrosRouteImport } from './routes/_authenticated/membros'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedMovimentacoesRouteImport } from './routes/_authenticated/movimentacoes'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedPermissoesRouteImport } from './routes/_authenticated/permissoes'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedRankingsRouteImport } from './routes/_authenticated/rankings'
import { Route as AuthenticatedTicketsRouteImport } from './routes/_authenticated/tickets'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as DevDiscordIdRouteImport } from './routes/dev.$discordId'
import { Route as DevmlcDiscordIdRouteImport } from './routes/devmlc.$discordId'
import { Route as AuthenticatedAusenciasTabRouteImport } from './routes/_authenticated/ausencias.$tab'
import { Route as AuthenticatedCeoTabRouteImport } from './routes/_authenticated/ceo.$tab'
import { Route as AuthenticatedCeoNotificacoesRouteImport } from './routes/_authenticated/ceo.notificacoes'
import { Route as AuthenticatedConfiguracoesTabRouteImport } from './routes/_authenticated/configuracoes.$tab'
import { Route as AuthenticatedDevIndexRouteImport } from './routes/_authenticated/dev.index'
import { Route as AuthenticatedDevPageRouteImport } from './routes/_authenticated/dev.$page'
import { Route as AuthenticatedDevBotRouteImport } from './routes/_authenticated/dev.bot'
import { Route as AuthenticatedDevConfiguracaoRouteImport } from './routes/_authenticated/dev.configuracao'
import { Route as AuthenticatedDevDesempenhoRouteImport } from './routes/_authenticated/dev.desempenho'
import { Route as AuthenticatedDevMenuLateralRouteImport } from './routes/_authenticated/dev.menu-lateral'
import { Route as AuthenticatedDevNotificacoesRouteImport } from './routes/_authenticated/dev.notificacoes'
import { Route as AuthenticatedDevPatchNotesRouteImport } from './routes/_authenticated/dev.patch-notes'
import { Route as AuthenticatedDevPermissoesRouteImport } from './routes/_authenticated/dev.permissoes'
import { Route as AuthenticatedHierarquiaTabRouteImport } from './routes/_authenticated/hierarquia.$tab'
import { Route as AuthenticatedLivesTabRouteImport } from './routes/_authenticated/lives.$tab'
import { Route as AuthenticatedMetasTabRouteImport } from './routes/_authenticated/metas.$tab'
import { Route as AuthenticatedMovimentacoesTabRouteImport } from './routes/_authenticated/movimentacoes.$tab'
import { Route as AuthenticatedPerfilHandleRouteImport } from './routes/_authenticated/perfil.$handle'
import { Route as AuthenticatedPerfilAparenciaRouteImport } from './routes/_authenticated/perfil.aparencia'
import { Route as AuthenticatedPerfilDadosRouteImport } from './routes/_authenticated/perfil.dados'
import { Route as AuthenticatedRankingsTabRouteImport } from './routes/_authenticated/rankings.$tab'
import { Route as AuthenticatedTicketsTabRouteImport } from './routes/_authenticated/tickets.$tab'
import { Route as DevmlcDiscordidDiscordIdRouteImport } from './routes/devmlc.discordid.$discordId'
import { Route as AuthenticatedCeoTabSubtabRouteImport } from './routes/_authenticated/ceo.$tab.$subtab'
import { Route as AuthenticatedDevPageTabRouteImport } from './routes/_authenticated/dev.$page.$tab'
import { Route as AuthenticatedDevConfiguracaoTabRouteImport } from './routes/_authenticated/dev.configuracao.$tab'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandleRoute = HandleRouteImport.update({
  id: '/$handle',
  path: '/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAtualizacoesRoute =
  AuthenticatedAtualizacoesRouteImport.update({
    id: '/atualizacoes',
    path: '/atualizacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAusenciasRoute = AuthenticatedAusenciasRouteImport.update({
  id: '/ausencias',
  path: '/ausencias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAvisosRoute = AuthenticatedAvisosRouteImport.update({
  id: '/avisos',
  path: '/avisos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBausRoute = AuthenticatedBausRouteImport.update({
  id: '/baus',
  path: '/baus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCargosRoute = AuthenticatedCargosRouteImport.update({
  id: '/cargos',
  path: '/cargos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCategoriasRoute = AuthenticatedCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCeoRoute = AuthenticatedCeoRouteImport.update({
  id: '/ceo',
  path: '/ceo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDesempenhoRoute = AuthenticatedDesempenhoRouteImport.update({
  id: '/desempenho',
  path: '/desempenho',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEstoqueRoute = AuthenticatedEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFundoCaixaRoute = AuthenticatedFundoCaixaRouteImport.update({
  id: '/fundo-caixa',
  path: '/fundo-caixa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHierarquiaRoute = AuthenticatedHierarquiaRouteImport.update({
  id: '/hierarquia',
  path: '/hierarquia',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLivesRoute = AuthenticatedLivesRouteImport.update({
  id: '/lives',
  path: '/lives',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMembrosRoute = AuthenticatedMembrosRouteImport.update({
  id: '/membros',
  path: '/membros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMovimentacoesRoute =
  AuthenticatedMovimentacoesRouteImport.update({
    id: '/movimentacoes',
    path: '/movimentacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPermissoesRoute = AuthenticatedPermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingsRoute = AuthenticatedRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsRoute = AuthenticatedTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DevDiscordIdRoute = DevDiscordIdRouteImport.update({
  id: '/dev/$discordId',
  path: '/dev/$discordId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevmlcDiscordIdRoute = DevmlcDiscordIdRouteImport.update({
  id: '/devmlc/$discordId',
  path: '/devmlc/$discordId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAusenciasTabRoute =
  AuthenticatedAusenciasTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => AuthenticatedAusenciasRoute,
  } as any)
const AuthenticatedCeoTabRoute = AuthenticatedCeoTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => AuthenticatedCeoRoute,
} as any)
const AuthenticatedCeoNotificacoesRoute =
  AuthenticatedCeoNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedCeoRoute,
  } as any)
const AuthenticatedConfiguracoesTabRoute =
  AuthenticatedConfiguracoesTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedDevIndexRoute = AuthenticatedDevIndexRouteImport.update({
  id: '/dev/',
  path: '/dev/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevPageRoute = AuthenticatedDevPageRouteImport.update({
  id: '/dev/$page',
  path: '/dev/$page',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevBotRoute = AuthenticatedDevBotRouteImport.update({
  id: '/dev/bot',
  path: '/dev/bot',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevConfiguracaoRoute =
  AuthenticatedDevConfiguracaoRouteImport.update({
    id: '/dev/configuracao',
    path: '/dev/configuracao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevDesempenhoRoute =
  AuthenticatedDevDesempenhoRouteImport.update({
    id: '/dev/desempenho',
    path: '/dev/desempenho',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevMenuLateralRoute =
  AuthenticatedDevMenuLateralRouteImport.update({
    id: '/dev/menu-lateral',
    path: '/dev/menu-lateral',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevNotificacoesRoute =
  AuthenticatedDevNotificacoesRouteImport.update({
    id: '/dev/notificacoes',
    path: '/dev/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevPatchNotesRoute =
  AuthenticatedDevPatchNotesRouteImport.update({
    id: '/dev/patch-notes',
    path: '/dev/patch-notes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevPermissoesRoute =
  AuthenticatedDevPermissoesRouteImport.update({
    id: '/dev/permissoes',
    path: '/dev/permissoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHierarquiaTabRoute =
  AuthenticatedHierarquiaTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => AuthenticatedHierarquiaRoute,
  } as any)
const AuthenticatedLivesTabRoute = AuthenticatedLivesTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => AuthenticatedLivesRoute,
} as any)
const AuthenticatedMetasTabRoute = AuthenticatedMetasTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => AuthenticatedMetasRoute,
} as any)
const AuthenticatedMovimentacoesTabRoute =
  AuthenticatedMovimentacoesTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => AuthenticatedMovimentacoesRoute,
  } as any)
const AuthenticatedPerfilHandleRoute =
  AuthenticatedPerfilHandleRouteImport.update({
    id: '/$handle',
    path: '/$handle',
    getParentRoute: () => AuthenticatedPerfilRoute,
  } as any)
const AuthenticatedPerfilAparenciaRoute =
  AuthenticatedPerfilAparenciaRouteImport.update({
    id: '/aparencia',
    path: '/aparencia',
    getParentRoute: () => AuthenticatedPerfilRoute,
  } as any)
const AuthenticatedPerfilDadosRoute =
  AuthenticatedPerfilDadosRouteImport.update({
    id: '/dados',
    path: '/dados',
    getParentRoute: () => AuthenticatedPerfilRoute,
  } as any)
const AuthenticatedRankingsTabRoute =
  AuthenticatedRankingsTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => AuthenticatedRankingsRoute,
  } as any)
const AuthenticatedTicketsTabRoute = AuthenticatedTicketsTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => AuthenticatedTicketsRoute,
} as any)
const DevmlcDiscordidDiscordIdRoute =
  DevmlcDiscordidDiscordIdRouteImport.update({
    id: '/devmlc/discordid/$discordId',
    path: '/devmlc/discordid/$discordId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedCeoTabSubtabRoute =
  AuthenticatedCeoTabSubtabRouteImport.update({
    id: '/$subtab',
    path: '/$subtab',
    getParentRoute: () => AuthenticatedCeoTabRoute,
  } as any)
const AuthenticatedDevPageTabRoute = AuthenticatedDevPageTabRouteImport.update({
  id: '/$tab',
  path: '/$tab',
  getParentRoute: () => AuthenticatedDevPageRoute,
} as any)
const AuthenticatedDevConfiguracaoTabRoute =
  AuthenticatedDevConfiguracaoTabRouteImport.update({
    id: '/$tab',
    path: '/$tab',
    getParentRoute: () => AuthenticatedDevConfiguracaoRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/atualizacoes': typeof AuthenticatedAtualizacoesRoute
  '/ausencias': typeof AuthenticatedAusenciasRouteWithChildren
  '/avisos': typeof AuthenticatedAvisosRoute
  '/baus': typeof AuthenticatedBausRoute
  '/cargos': typeof AuthenticatedCargosRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/ceo': typeof AuthenticatedCeoRouteWithChildren
  '/chat': typeof AuthenticatedChatRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/desempenho': typeof AuthenticatedDesempenhoRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/fundo-caixa': typeof AuthenticatedFundoCaixaRoute
  '/hierarquia': typeof AuthenticatedHierarquiaRouteWithChildren
  '/lives': typeof AuthenticatedLivesRouteWithChildren
  '/logs': typeof AuthenticatedLogsRoute
  '/membros': typeof AuthenticatedMembrosRoute
  '/metas': typeof AuthenticatedMetasRouteWithChildren
  '/movimentacoes': typeof AuthenticatedMovimentacoesRouteWithChildren
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/permissoes': typeof AuthenticatedPermissoesRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/rankings': typeof AuthenticatedRankingsRouteWithChildren
  '/tickets': typeof AuthenticatedTicketsRouteWithChildren
  '/vendas': typeof AuthenticatedVendasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev/$discordId': typeof DevDiscordIdRoute
  '/devmlc/$discordId': typeof DevmlcDiscordIdRoute
  '/ausencias/$tab': typeof AuthenticatedAusenciasTabRoute
  '/ceo/$tab': typeof AuthenticatedCeoTabRouteWithChildren
  '/ceo/notificacoes': typeof AuthenticatedCeoNotificacoesRoute
  '/configuracoes/$tab': typeof AuthenticatedConfiguracoesTabRoute
  '/dev/$page': typeof AuthenticatedDevPageRouteWithChildren
  '/dev/bot': typeof AuthenticatedDevBotRoute
  '/dev/configuracao': typeof AuthenticatedDevConfiguracaoRouteWithChildren
  '/dev/desempenho': typeof AuthenticatedDevDesempenhoRoute
  '/dev/menu-lateral': typeof AuthenticatedDevMenuLateralRoute
  '/dev/notificacoes': typeof AuthenticatedDevNotificacoesRoute
  '/dev/patch-notes': typeof AuthenticatedDevPatchNotesRoute
  '/dev/permissoes': typeof AuthenticatedDevPermissoesRoute
  '/hierarquia/$tab': typeof AuthenticatedHierarquiaTabRoute
  '/lives/$tab': typeof AuthenticatedLivesTabRoute
  '/metas/$tab': typeof AuthenticatedMetasTabRoute
  '/movimentacoes/$tab': typeof AuthenticatedMovimentacoesTabRoute
  '/perfil/$handle': typeof AuthenticatedPerfilHandleRoute
  '/perfil/aparencia': typeof AuthenticatedPerfilAparenciaRoute
  '/perfil/dados': typeof AuthenticatedPerfilDadosRoute
  '/rankings/$tab': typeof AuthenticatedRankingsTabRoute
  '/tickets/$tab': typeof AuthenticatedTicketsTabRoute
  '/devmlc/discordid/$discordId': typeof DevmlcDiscordidDiscordIdRoute
  '/dev/': typeof AuthenticatedDevIndexRoute
  '/ceo/$tab/$subtab': typeof AuthenticatedCeoTabSubtabRoute
  '/dev/$page/$tab': typeof AuthenticatedDevPageTabRoute
  '/dev/configuracao/$tab': typeof AuthenticatedDevConfiguracaoTabRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$handle': typeof HandleRoute
  '/atualizacoes': typeof AuthenticatedAtualizacoesRoute
  '/ausencias': typeof AuthenticatedAusenciasRouteWithChildren
  '/avisos': typeof AuthenticatedAvisosRoute
  '/baus': typeof AuthenticatedBausRoute
  '/cargos': typeof AuthenticatedCargosRoute
  '/categorias': typeof AuthenticatedCategoriasRoute
  '/ceo': typeof AuthenticatedCeoRouteWithChildren
  '/chat': typeof AuthenticatedChatRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/desempenho': typeof AuthenticatedDesempenhoRoute
  '/estoque': typeof AuthenticatedEstoqueRoute
  '/fundo-caixa': typeof AuthenticatedFundoCaixaRoute
  '/hierarquia': typeof AuthenticatedHierarquiaRouteWithChildren
  '/lives': typeof AuthenticatedLivesRouteWithChildren
  '/logs': typeof AuthenticatedLogsRoute
  '/membros': typeof AuthenticatedMembrosRoute
  '/metas': typeof AuthenticatedMetasRouteWithChildren
  '/movimentacoes': typeof AuthenticatedMovimentacoesRouteWithChildren
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/permissoes': typeof AuthenticatedPermissoesRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/rankings': typeof AuthenticatedRankingsRouteWithChildren
  '/tickets': typeof AuthenticatedTicketsRouteWithChildren
  '/vendas': typeof AuthenticatedVendasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev/$discordId': typeof DevDiscordIdRoute
  '/devmlc/$discordId': typeof DevmlcDiscordIdRoute
  '/ausencias/$tab': typeof AuthenticatedAusenciasTabRoute
  '/ceo/$tab': typeof AuthenticatedCeoTabRouteWithChildren
  '/ceo/notificacoes': typeof AuthenticatedCeoNotificacoesRoute
  '/configuracoes/$tab': typeof AuthenticatedConfiguracoesTabRoute
  '/dev/$page': typeof AuthenticatedDevPageRouteWithChildren
  '/dev/bot': typeof AuthenticatedDevBotRoute
  '/dev/configuracao': typeof AuthenticatedDevConfiguracaoRouteWithChildren
  '/dev/desempenho': typeof AuthenticatedDevDesempenhoRoute
  '/dev/menu-lateral': typeof AuthenticatedDevMenuLateralRoute
  '/dev/notificacoes': typeof AuthenticatedDevNotificacoesRoute
  '/dev/patch-notes': typeof AuthenticatedDevPatchNotesRoute
  '/dev/permissoes': typeof AuthenticatedDevPermissoesRoute
  '/hierarquia/$tab': typeof AuthenticatedHierarquiaTabRoute
  '/lives/$tab': typeof AuthenticatedLivesTabRoute
  '/metas/$tab': typeof AuthenticatedMetasTabRoute
  '/movimentacoes/$tab': typeof AuthenticatedMovimentacoesTabRoute
  '/perfil/$handle': typeof AuthenticatedPerfilHandleRoute
  '/perfil/aparencia': typeof AuthenticatedPerfilAparenciaRoute
  '/perfil/dados': typeof AuthenticatedPerfilDadosRoute
  '/rankings/$tab': typeof AuthenticatedRankingsTabRoute
  '/tickets/$tab': typeof AuthenticatedTicketsTabRoute
  '/devmlc/discordid/$discordId': typeof DevmlcDiscordidDiscordIdRoute
  '/dev': typeof AuthenticatedDevIndexRoute
  '/ceo/$tab/$subtab': typeof AuthenticatedCeoTabSubtabRoute
  '/dev/$page/$tab': typeof AuthenticatedDevPageTabRoute
  '/dev/configuracao/$tab': typeof AuthenticatedDevConfiguracaoTabRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$handle': typeof HandleRoute
  '/_authenticated/atualizacoes': typeof AuthenticatedAtualizacoesRoute
  '/_authenticated/ausencias': typeof AuthenticatedAusenciasRouteWithChildren
  '/_authenticated/avisos': typeof AuthenticatedAvisosRoute
  '/_authenticated/baus': typeof AuthenticatedBausRoute
  '/_authenticated/cargos': typeof AuthenticatedCargosRoute
  '/_authenticated/categorias': typeof AuthenticatedCategoriasRoute
  '/_authenticated/ceo': typeof AuthenticatedCeoRouteWithChildren
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/desempenho': typeof AuthenticatedDesempenhoRoute
  '/_authenticated/estoque': typeof AuthenticatedEstoqueRoute
  '/_authenticated/fundo-caixa': typeof AuthenticatedFundoCaixaRoute
  '/_authenticated/hierarquia': typeof AuthenticatedHierarquiaRouteWithChildren
  '/_authenticated/lives': typeof AuthenticatedLivesRouteWithChildren
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/membros': typeof AuthenticatedMembrosRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRouteWithChildren
  '/_authenticated/movimentacoes': typeof AuthenticatedMovimentacoesRouteWithChildren
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRouteWithChildren
  '/_authenticated/permissoes': typeof AuthenticatedPermissoesRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/rankings': typeof AuthenticatedRankingsRouteWithChildren
  '/_authenticated/tickets': typeof AuthenticatedTicketsRouteWithChildren
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dev/$discordId': typeof DevDiscordIdRoute
  '/devmlc/$discordId': typeof DevmlcDiscordIdRoute
  '/_authenticated/ausencias/$tab': typeof AuthenticatedAusenciasTabRoute
  '/_authenticated/ceo/$tab': typeof AuthenticatedCeoTabRouteWithChildren
  '/_authenticated/ceo/notificacoes': typeof AuthenticatedCeoNotificacoesRoute
  '/_authenticated/configuracoes/$tab': typeof AuthenticatedConfiguracoesTabRoute
  '/_authenticated/dev/$page': typeof AuthenticatedDevPageRouteWithChildren
  '/_authenticated/dev/bot': typeof AuthenticatedDevBotRoute
  '/_authenticated/dev/configuracao': typeof AuthenticatedDevConfiguracaoRouteWithChildren
  '/_authenticated/dev/desempenho': typeof AuthenticatedDevDesempenhoRoute
  '/_authenticated/dev/menu-lateral': typeof AuthenticatedDevMenuLateralRoute
  '/_authenticated/dev/notificacoes': typeof AuthenticatedDevNotificacoesRoute
  '/_authenticated/dev/patch-notes': typeof AuthenticatedDevPatchNotesRoute
  '/_authenticated/dev/permissoes': typeof AuthenticatedDevPermissoesRoute
  '/_authenticated/hierarquia/$tab': typeof AuthenticatedHierarquiaTabRoute
  '/_authenticated/lives/$tab': typeof AuthenticatedLivesTabRoute
  '/_authenticated/metas/$tab': typeof AuthenticatedMetasTabRoute
  '/_authenticated/movimentacoes/$tab': typeof AuthenticatedMovimentacoesTabRoute
  '/_authenticated/perfil/$handle': typeof AuthenticatedPerfilHandleRoute
  '/_authenticated/perfil/aparencia': typeof AuthenticatedPerfilAparenciaRoute
  '/_authenticated/perfil/dados': typeof AuthenticatedPerfilDadosRoute
  '/_authenticated/rankings/$tab': typeof AuthenticatedRankingsTabRoute
  '/_authenticated/tickets/$tab': typeof AuthenticatedTicketsTabRoute
  '/devmlc/discordid/$discordId': typeof DevmlcDiscordidDiscordIdRoute
  '/_authenticated/dev/': typeof AuthenticatedDevIndexRoute
  '/_authenticated/ceo/$tab/$subtab': typeof AuthenticatedCeoTabSubtabRoute
  '/_authenticated/dev/$page/$tab': typeof AuthenticatedDevPageTabRoute
  '/_authenticated/dev/configuracao/$tab': typeof AuthenticatedDevConfiguracaoTabRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$handle'
    | '/atualizacoes'
    | '/ausencias'
    | '/avisos'
    | '/baus'
    | '/cargos'
    | '/categorias'
    | '/ceo'
    | '/chat'
    | '/configuracoes'
    | '/dashboard'
    | '/desempenho'
    | '/estoque'
    | '/fundo-caixa'
    | '/hierarquia'
    | '/lives'
    | '/logs'
    | '/membros'
    | '/metas'
    | '/movimentacoes'
    | '/notificacoes'
    | '/perfil'
    | '/permissoes'
    | '/produtos'
    | '/rankings'
    | '/tickets'
    | '/vendas'
    | '/auth/callback'
    | '/dev/$discordId'
    | '/devmlc/$discordId'
    | '/ausencias/$tab'
    | '/ceo/$tab'
    | '/ceo/notificacoes'
    | '/configuracoes/$tab'
    | '/dev/$page'
    | '/dev/bot'
    | '/dev/configuracao'
    | '/dev/desempenho'
    | '/dev/menu-lateral'
    | '/dev/notificacoes'
    | '/dev/patch-notes'
    | '/dev/permissoes'
    | '/hierarquia/$tab'
    | '/lives/$tab'
    | '/metas/$tab'
    | '/movimentacoes/$tab'
    | '/perfil/$handle'
    | '/perfil/aparencia'
    | '/perfil/dados'
    | '/rankings/$tab'
    | '/tickets/$tab'
    | '/devmlc/discordid/$discordId'
    | '/dev/'
    | '/ceo/$tab/$subtab'
    | '/dev/$page/$tab'
    | '/dev/configuracao/$tab'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$handle'
    | '/atualizacoes'
    | '/ausencias'
    | '/avisos'
    | '/baus'
    | '/cargos'
    | '/categorias'
    | '/ceo'
    | '/chat'
    | '/configuracoes'
    | '/dashboard'
    | '/desempenho'
    | '/estoque'
    | '/fundo-caixa'
    | '/hierarquia'
    | '/lives'
    | '/logs'
    | '/membros'
    | '/metas'
    | '/movimentacoes'
    | '/notificacoes'
    | '/perfil'
    | '/permissoes'
    | '/produtos'
    | '/rankings'
    | '/tickets'
    | '/vendas'
    | '/auth/callback'
    | '/dev/$discordId'
    | '/devmlc/$discordId'
    | '/ausencias/$tab'
    | '/ceo/$tab'
    | '/ceo/notificacoes'
    | '/configuracoes/$tab'
    | '/dev/$page'
    | '/dev/bot'
    | '/dev/configuracao'
    | '/dev/desempenho'
    | '/dev/menu-lateral'
    | '/dev/notificacoes'
    | '/dev/patch-notes'
    | '/dev/permissoes'
    | '/hierarquia/$tab'
    | '/lives/$tab'
    | '/metas/$tab'
    | '/movimentacoes/$tab'
    | '/perfil/$handle'
    | '/perfil/aparencia'
    | '/perfil/dados'
    | '/rankings/$tab'
    | '/tickets/$tab'
    | '/devmlc/discordid/$discordId'
    | '/dev'
    | '/ceo/$tab/$subtab'
    | '/dev/$page/$tab'
    | '/dev/configuracao/$tab'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$handle'
    | '/_authenticated/atualizacoes'
    | '/_authenticated/ausencias'
    | '/_authenticated/avisos'
    | '/_authenticated/baus'
    | '/_authenticated/cargos'
    | '/_authenticated/categorias'
    | '/_authenticated/ceo'
    | '/_authenticated/chat'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/desempenho'
    | '/_authenticated/estoque'
    | '/_authenticated/fundo-caixa'
    | '/_authenticated/hierarquia'
    | '/_authenticated/lives'
    | '/_authenticated/logs'
    | '/_authenticated/membros'
    | '/_authenticated/metas'
    | '/_authenticated/movimentacoes'
    | '/_authenticated/notificacoes'
    | '/_authenticated/perfil'
    | '/_authenticated/permissoes'
    | '/_authenticated/produtos'
    | '/_authenticated/rankings'
    | '/_authenticated/tickets'
    | '/_authenticated/vendas'
    | '/auth/callback'
    | '/dev/$discordId'
    | '/devmlc/$discordId'
    | '/_authenticated/ausencias/$tab'
    | '/_authenticated/ceo/$tab'
    | '/_authenticated/ceo/notificacoes'
    | '/_authenticated/configuracoes/$tab'
    | '/_authenticated/dev/$page'
    | '/_authenticated/dev/bot'
    | '/_authenticated/dev/configuracao'
    | '/_authenticated/dev/desempenho'
    | '/_authenticated/dev/menu-lateral'
    | '/_authenticated/dev/notificacoes'
    | '/_authenticated/dev/patch-notes'
    | '/_authenticated/dev/permissoes'
    | '/_authenticated/hierarquia/$tab'
    | '/_authenticated/lives/$tab'
    | '/_authenticated/metas/$tab'
    | '/_authenticated/movimentacoes/$tab'
    | '/_authenticated/perfil/$handle'
    | '/_authenticated/perfil/aparencia'
    | '/_authenticated/perfil/dados'
    | '/_authenticated/rankings/$tab'
    | '/_authenticated/tickets/$tab'
    | '/devmlc/discordid/$discordId'
    | '/_authenticated/dev/'
    | '/_authenticated/ceo/$tab/$subtab'
    | '/_authenticated/dev/$page/$tab'
    | '/_authenticated/dev/configuracao/$tab'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  HandleRoute: typeof HandleRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  DevDiscordIdRoute: typeof DevDiscordIdRoute
  DevmlcDiscordIdRoute: typeof DevmlcDiscordIdRoute
  DevmlcDiscordidDiscordIdRoute: typeof DevmlcDiscordidDiscordIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$handle': {
      id: '/$handle'
      path: '/$handle'
      fullPath: '/$handle'
      preLoaderRoute: typeof HandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atualizacoes': {
      id: '/_authenticated/atualizacoes'
      path: '/atualizacoes'
      fullPath: '/atualizacoes'
      preLoaderRoute: typeof AuthenticatedAtualizacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ausencias': {
      id: '/_authenticated/ausencias'
      path: '/ausencias'
      fullPath: '/ausencias'
      preLoaderRoute: typeof AuthenticatedAusenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/avisos': {
      id: '/_authenticated/avisos'
      path: '/avisos'
      fullPath: '/avisos'
      preLoaderRoute: typeof AuthenticatedAvisosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/baus': {
      id: '/_authenticated/baus'
      path: '/baus'
      fullPath: '/baus'
      preLoaderRoute: typeof AuthenticatedBausRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cargos': {
      id: '/_authenticated/cargos'
      path: '/cargos'
      fullPath: '/cargos'
      preLoaderRoute: typeof AuthenticatedCargosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/categorias': {
      id: '/_authenticated/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AuthenticatedCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ceo': {
      id: '/_authenticated/ceo'
      path: '/ceo'
      fullPath: '/ceo'
      preLoaderRoute: typeof AuthenticatedCeoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/desempenho': {
      id: '/_authenticated/desempenho'
      path: '/desempenho'
      fullPath: '/desempenho'
      preLoaderRoute: typeof AuthenticatedDesempenhoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estoque': {
      id: '/_authenticated/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof AuthenticatedEstoqueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fundo-caixa': {
      id: '/_authenticated/fundo-caixa'
      path: '/fundo-caixa'
      fullPath: '/fundo-caixa'
      preLoaderRoute: typeof AuthenticatedFundoCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hierarquia': {
      id: '/_authenticated/hierarquia'
      path: '/hierarquia'
      fullPath: '/hierarquia'
      preLoaderRoute: typeof AuthenticatedHierarquiaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lives': {
      id: '/_authenticated/lives'
      path: '/lives'
      fullPath: '/lives'
      preLoaderRoute: typeof AuthenticatedLivesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/membros': {
      id: '/_authenticated/membros'
      path: '/membros'
      fullPath: '/membros'
      preLoaderRoute: typeof AuthenticatedMembrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/movimentacoes': {
      id: '/_authenticated/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/movimentacoes'
      preLoaderRoute: typeof AuthenticatedMovimentacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/permissoes': {
      id: '/_authenticated/permissoes'
      path: '/permissoes'
      fullPath: '/permissoes'
      preLoaderRoute: typeof AuthenticatedPermissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rankings': {
      id: '/_authenticated/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof AuthenticatedRankingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets': {
      id: '/_authenticated/tickets'
      path: '/tickets'
      fullPath: '/tickets'
      preLoaderRoute: typeof AuthenticatedTicketsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/$discordId': {
      id: '/dev/$discordId'
      path: '/dev/$discordId'
      fullPath: '/dev/$discordId'
      preLoaderRoute: typeof DevDiscordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devmlc/$discordId': {
      id: '/devmlc/$discordId'
      path: '/devmlc/$discordId'
      fullPath: '/devmlc/$discordId'
      preLoaderRoute: typeof DevmlcDiscordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ausencias/$tab': {
      id: '/_authenticated/ausencias/$tab'
      path: '/$tab'
      fullPath: '/ausencias/$tab'
      preLoaderRoute: typeof AuthenticatedAusenciasTabRouteImport
      parentRoute: typeof AuthenticatedAusenciasRoute
    }
    '/_authenticated/ceo/$tab': {
      id: '/_authenticated/ceo/$tab'
      path: '/$tab'
      fullPath: '/ceo/$tab'
      preLoaderRoute: typeof AuthenticatedCeoTabRouteImport
      parentRoute: typeof AuthenticatedCeoRoute
    }
    '/_authenticated/ceo/notificacoes': {
      id: '/_authenticated/ceo/notificacoes'
      path: '/notificacoes'
      fullPath: '/ceo/notificacoes'
      preLoaderRoute: typeof AuthenticatedCeoNotificacoesRouteImport
      parentRoute: typeof AuthenticatedCeoRoute
    }
    '/_authenticated/configuracoes/$tab': {
      id: '/_authenticated/configuracoes/$tab'
      path: '/$tab'
      fullPath: '/configuracoes/$tab'
      preLoaderRoute: typeof AuthenticatedConfiguracoesTabRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/dev/': {
      id: '/_authenticated/dev/'
      path: '/dev'
      fullPath: '/dev/'
      preLoaderRoute: typeof AuthenticatedDevIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev/$page': {
      id: '/_authenticated/dev/$page'
      path: '/dev/$page'
      fullPath: '/dev/$page'
      preLoaderRoute: typeof AuthenticatedDevPageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev/bot': {
      id: '/_authenticated/dev/bot'
      path: '/dev/bot'
      fullPath: '/dev/bot'
      preLoaderRoute: typeof AuthenticatedDevBotRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev/configuracao': {
      id: '/_authenticated/dev/configuracao'
      path: '/dev/configuracao'
      fullPath: '/dev/configuracao'
      preLoaderRoute: typeof AuthenticatedDevConfiguracaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev/desempenho': {
      id: '/_authenticated/dev/desempenho'
      path: '/dev/desempenho'
      fullPath: '/dev/desempenho'
      preLoaderRoute: typeof AuthenticatedDevDesempenhoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev/menu-lateral': {
      id: '/_authenticated/dev/menu-lateral'
      path: '/dev/menu-lateral'
      fullPath: '/dev/menu-lateral'
      preLoaderRoute: typeof AuthenticatedDevMenuLateralRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev/notificacoes': {
      id: '/_authenticated/dev/notificacoes'
      path: '/dev/notificacoes'
      fullPath: '/dev/notificacoes'
      preLoaderRoute: typeof AuthenticatedDevNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev/patch-notes': {
      id: '/_authenticated/dev/patch-notes'
      path: '/dev/patch-notes'
      fullPath: '/dev/patch-notes'
      preLoaderRoute: typeof AuthenticatedDevPatchNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev/permissoes': {
      id: '/_authenticated/dev/permissoes'
      path: '/dev/permissoes'
      fullPath: '/dev/permissoes'
      preLoaderRoute: typeof AuthenticatedDevPermissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hierarquia/$tab': {
      id: '/_authenticated/hierarquia/$tab'
      path: '/$tab'
      fullPath: '/hierarquia/$tab'
      preLoaderRoute: typeof AuthenticatedHierarquiaTabRouteImport
      parentRoute: typeof AuthenticatedHierarquiaRoute
    }
    '/_authenticated/lives/$tab': {
      id: '/_authenticated/lives/$tab'
      path: '/$tab'
      fullPath: '/lives/$tab'
      preLoaderRoute: typeof AuthenticatedLivesTabRouteImport
      parentRoute: typeof AuthenticatedLivesRoute
    }
    '/_authenticated/metas/$tab': {
      id: '/_authenticated/metas/$tab'
      path: '/$tab'
      fullPath: '/metas/$tab'
      preLoaderRoute: typeof AuthenticatedMetasTabRouteImport
      parentRoute: typeof AuthenticatedMetasRoute
    }
    '/_authenticated/movimentacoes/$tab': {
      id: '/_authenticated/movimentacoes/$tab'
      path: '/$tab'
      fullPath: '/movimentacoes/$tab'
      preLoaderRoute: typeof AuthenticatedMovimentacoesTabRouteImport
      parentRoute: typeof AuthenticatedMovimentacoesRoute
    }
    '/_authenticated/perfil/$handle': {
      id: '/_authenticated/perfil/$handle'
      path: '/$handle'
      fullPath: '/perfil/$handle'
      preLoaderRoute: typeof AuthenticatedPerfilHandleRouteImport
      parentRoute: typeof AuthenticatedPerfilRoute
    }
    '/_authenticated/perfil/aparencia': {
      id: '/_authenticated/perfil/aparencia'
      path: '/aparencia'
      fullPath: '/perfil/aparencia'
      preLoaderRoute: typeof AuthenticatedPerfilAparenciaRouteImport
      parentRoute: typeof AuthenticatedPerfilRoute
    }
    '/_authenticated/perfil/dados': {
      id: '/_authenticated/perfil/dados'
      path: '/dados'
      fullPath: '/perfil/dados'
      preLoaderRoute: typeof AuthenticatedPerfilDadosRouteImport
      parentRoute: typeof AuthenticatedPerfilRoute
    }
    '/_authenticated/rankings/$tab': {
      id: '/_authenticated/rankings/$tab'
      path: '/$tab'
      fullPath: '/rankings/$tab'
      preLoaderRoute: typeof AuthenticatedRankingsTabRouteImport
      parentRoute: typeof AuthenticatedRankingsRoute
    }
    '/_authenticated/tickets/$tab': {
      id: '/_authenticated/tickets/$tab'
      path: '/$tab'
      fullPath: '/tickets/$tab'
      preLoaderRoute: typeof AuthenticatedTicketsTabRouteImport
      parentRoute: typeof AuthenticatedTicketsRoute
    }
    '/devmlc/discordid/$discordId': {
      id: '/devmlc/discordid/$discordId'
      path: '/devmlc/discordid/$discordId'
      fullPath: '/devmlc/discordid/$discordId'
      preLoaderRoute: typeof DevmlcDiscordidDiscordIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ceo/$tab/$subtab': {
      id: '/_authenticated/ceo/$tab/$subtab'
      path: '/$subtab'
      fullPath: '/ceo/$tab/$subtab'
      preLoaderRoute: typeof AuthenticatedCeoTabSubtabRouteImport
      parentRoute: typeof AuthenticatedCeoTabRoute
    }
    '/_authenticated/dev/$page/$tab': {
      id: '/_authenticated/dev/$page/$tab'
      path: '/$tab'
      fullPath: '/dev/$page/$tab'
      preLoaderRoute: typeof AuthenticatedDevPageTabRouteImport
      parentRoute: typeof AuthenticatedDevPageRoute
    }
    '/_authenticated/dev/configuracao/$tab': {
      id: '/_authenticated/dev/configuracao/$tab'
      path: '/$tab'
      fullPath: '/dev/configuracao/$tab'
      preLoaderRoute: typeof AuthenticatedDevConfiguracaoTabRouteImport
      parentRoute: typeof AuthenticatedDevConfiguracaoRoute
    }
  }
}

interface AuthenticatedAusenciasRouteChildren {
  AuthenticatedAusenciasTabRoute: typeof AuthenticatedAusenciasTabRoute
}

const AuthenticatedAusenciasRouteChildren: AuthenticatedAusenciasRouteChildren =
  {
    AuthenticatedAusenciasTabRoute: AuthenticatedAusenciasTabRoute,
  }

const AuthenticatedAusenciasRouteWithChildren =
  AuthenticatedAusenciasRoute._addFileChildren(
    AuthenticatedAusenciasRouteChildren,
  )

interface AuthenticatedCeoTabRouteChildren {
  AuthenticatedCeoTabSubtabRoute: typeof AuthenticatedCeoTabSubtabRoute
}

const AuthenticatedCeoTabRouteChildren: AuthenticatedCeoTabRouteChildren = {
  AuthenticatedCeoTabSubtabRoute: AuthenticatedCeoTabSubtabRoute,
}

const AuthenticatedCeoTabRouteWithChildren =
  AuthenticatedCeoTabRoute._addFileChildren(AuthenticatedCeoTabRouteChildren)

interface AuthenticatedCeoRouteChildren {
  AuthenticatedCeoTabRoute: typeof AuthenticatedCeoTabRouteWithChildren
  AuthenticatedCeoNotificacoesRoute: typeof AuthenticatedCeoNotificacoesRoute
}

const AuthenticatedCeoRouteChildren: AuthenticatedCeoRouteChildren = {
  AuthenticatedCeoTabRoute: AuthenticatedCeoTabRouteWithChildren,
  AuthenticatedCeoNotificacoesRoute: AuthenticatedCeoNotificacoesRoute,
}

const AuthenticatedCeoRouteWithChildren =
  AuthenticatedCeoRoute._addFileChildren(AuthenticatedCeoRouteChildren)

interface AuthenticatedConfiguracoesRouteChildren {
  AuthenticatedConfiguracoesTabRoute: typeof AuthenticatedConfiguracoesTabRoute
}

const AuthenticatedConfiguracoesRouteChildren: AuthenticatedConfiguracoesRouteChildren =
  {
    AuthenticatedConfiguracoesTabRoute: AuthenticatedConfiguracoesTabRoute,
  }

const AuthenticatedConfiguracoesRouteWithChildren =
  AuthenticatedConfiguracoesRoute._addFileChildren(
    AuthenticatedConfiguracoesRouteChildren,
  )

interface AuthenticatedHierarquiaRouteChildren {
  AuthenticatedHierarquiaTabRoute: typeof AuthenticatedHierarquiaTabRoute
}

const AuthenticatedHierarquiaRouteChildren: AuthenticatedHierarquiaRouteChildren =
  {
    AuthenticatedHierarquiaTabRoute: AuthenticatedHierarquiaTabRoute,
  }

const AuthenticatedHierarquiaRouteWithChildren =
  AuthenticatedHierarquiaRoute._addFileChildren(
    AuthenticatedHierarquiaRouteChildren,
  )

interface AuthenticatedLivesRouteChildren {
  AuthenticatedLivesTabRoute: typeof AuthenticatedLivesTabRoute
}

const AuthenticatedLivesRouteChildren: AuthenticatedLivesRouteChildren = {
  AuthenticatedLivesTabRoute: AuthenticatedLivesTabRoute,
}

const AuthenticatedLivesRouteWithChildren =
  AuthenticatedLivesRoute._addFileChildren(AuthenticatedLivesRouteChildren)

interface AuthenticatedMetasRouteChildren {
  AuthenticatedMetasTabRoute: typeof AuthenticatedMetasTabRoute
}

const AuthenticatedMetasRouteChildren: AuthenticatedMetasRouteChildren = {
  AuthenticatedMetasTabRoute: AuthenticatedMetasTabRoute,
}

const AuthenticatedMetasRouteWithChildren =
  AuthenticatedMetasRoute._addFileChildren(AuthenticatedMetasRouteChildren)

interface AuthenticatedMovimentacoesRouteChildren {
  AuthenticatedMovimentacoesTabRoute: typeof AuthenticatedMovimentacoesTabRoute
}

const AuthenticatedMovimentacoesRouteChildren: AuthenticatedMovimentacoesRouteChildren =
  {
    AuthenticatedMovimentacoesTabRoute: AuthenticatedMovimentacoesTabRoute,
  }

const AuthenticatedMovimentacoesRouteWithChildren =
  AuthenticatedMovimentacoesRoute._addFileChildren(
    AuthenticatedMovimentacoesRouteChildren,
  )

interface AuthenticatedPerfilRouteChildren {
  AuthenticatedPerfilHandleRoute: typeof AuthenticatedPerfilHandleRoute
  AuthenticatedPerfilAparenciaRoute: typeof AuthenticatedPerfilAparenciaRoute
  AuthenticatedPerfilDadosRoute: typeof AuthenticatedPerfilDadosRoute
}

const AuthenticatedPerfilRouteChildren: AuthenticatedPerfilRouteChildren = {
  AuthenticatedPerfilHandleRoute: AuthenticatedPerfilHandleRoute,
  AuthenticatedPerfilAparenciaRoute: AuthenticatedPerfilAparenciaRoute,
  AuthenticatedPerfilDadosRoute: AuthenticatedPerfilDadosRoute,
}

const AuthenticatedPerfilRouteWithChildren =
  AuthenticatedPerfilRoute._addFileChildren(AuthenticatedPerfilRouteChildren)

interface AuthenticatedRankingsRouteChildren {
  AuthenticatedRankingsTabRoute: typeof AuthenticatedRankingsTabRoute
}

const AuthenticatedRankingsRouteChildren: AuthenticatedRankingsRouteChildren = {
  AuthenticatedRankingsTabRoute: AuthenticatedRankingsTabRoute,
}

const AuthenticatedRankingsRouteWithChildren =
  AuthenticatedRankingsRoute._addFileChildren(
    AuthenticatedRankingsRouteChildren,
  )

interface AuthenticatedTicketsRouteChildren {
  AuthenticatedTicketsTabRoute: typeof AuthenticatedTicketsTabRoute
}

const AuthenticatedTicketsRouteChildren: AuthenticatedTicketsRouteChildren = {
  AuthenticatedTicketsTabRoute: AuthenticatedTicketsTabRoute,
}

const AuthenticatedTicketsRouteWithChildren =
  AuthenticatedTicketsRoute._addFileChildren(AuthenticatedTicketsRouteChildren)

interface AuthenticatedDevPageRouteChildren {
  AuthenticatedDevPageTabRoute: typeof AuthenticatedDevPageTabRoute
}

const AuthenticatedDevPageRouteChildren: AuthenticatedDevPageRouteChildren = {
  AuthenticatedDevPageTabRoute: AuthenticatedDevPageTabRoute,
}

const AuthenticatedDevPageRouteWithChildren =
  AuthenticatedDevPageRoute._addFileChildren(AuthenticatedDevPageRouteChildren)

interface AuthenticatedDevConfiguracaoRouteChildren {
  AuthenticatedDevConfiguracaoTabRoute: typeof AuthenticatedDevConfiguracaoTabRoute
}

const AuthenticatedDevConfiguracaoRouteChildren: AuthenticatedDevConfiguracaoRouteChildren =
  {
    AuthenticatedDevConfiguracaoTabRoute: AuthenticatedDevConfiguracaoTabRoute,
  }

const AuthenticatedDevConfiguracaoRouteWithChildren =
  AuthenticatedDevConfiguracaoRoute._addFileChildren(
    AuthenticatedDevConfiguracaoRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAtualizacoesRoute: typeof AuthenticatedAtualizacoesRoute
  AuthenticatedAusenciasRoute: typeof AuthenticatedAusenciasRouteWithChildren
  AuthenticatedAvisosRoute: typeof AuthenticatedAvisosRoute
  AuthenticatedBausRoute: typeof AuthenticatedBausRoute
  AuthenticatedCargosRoute: typeof AuthenticatedCargosRoute
  AuthenticatedCategoriasRoute: typeof AuthenticatedCategoriasRoute
  AuthenticatedCeoRoute: typeof AuthenticatedCeoRouteWithChildren
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDesempenhoRoute: typeof AuthenticatedDesempenhoRoute
  AuthenticatedEstoqueRoute: typeof AuthenticatedEstoqueRoute
  AuthenticatedFundoCaixaRoute: typeof AuthenticatedFundoCaixaRoute
  AuthenticatedHierarquiaRoute: typeof AuthenticatedHierarquiaRouteWithChildren
  AuthenticatedLivesRoute: typeof AuthenticatedLivesRouteWithChildren
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedMembrosRoute: typeof AuthenticatedMembrosRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRouteWithChildren
  AuthenticatedMovimentacoesRoute: typeof AuthenticatedMovimentacoesRouteWithChildren
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRouteWithChildren
  AuthenticatedPermissoesRoute: typeof AuthenticatedPermissoesRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedRankingsRoute: typeof AuthenticatedRankingsRouteWithChildren
  AuthenticatedTicketsRoute: typeof AuthenticatedTicketsRouteWithChildren
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedDevPageRoute: typeof AuthenticatedDevPageRouteWithChildren
  AuthenticatedDevBotRoute: typeof AuthenticatedDevBotRoute
  AuthenticatedDevConfiguracaoRoute: typeof AuthenticatedDevConfiguracaoRouteWithChildren
  AuthenticatedDevDesempenhoRoute: typeof AuthenticatedDevDesempenhoRoute
  AuthenticatedDevMenuLateralRoute: typeof AuthenticatedDevMenuLateralRoute
  AuthenticatedDevNotificacoesRoute: typeof AuthenticatedDevNotificacoesRoute
  AuthenticatedDevPatchNotesRoute: typeof AuthenticatedDevPatchNotesRoute
  AuthenticatedDevPermissoesRoute: typeof AuthenticatedDevPermissoesRoute
  AuthenticatedDevIndexRoute: typeof AuthenticatedDevIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAtualizacoesRoute: AuthenticatedAtualizacoesRoute,
  AuthenticatedAusenciasRoute: AuthenticatedAusenciasRouteWithChildren,
  AuthenticatedAvisosRoute: AuthenticatedAvisosRoute,
  AuthenticatedBausRoute: AuthenticatedBausRoute,
  AuthenticatedCargosRoute: AuthenticatedCargosRoute,
  AuthenticatedCategoriasRoute: AuthenticatedCategoriasRoute,
  AuthenticatedCeoRoute: AuthenticatedCeoRouteWithChildren,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDesempenhoRoute: AuthenticatedDesempenhoRoute,
  AuthenticatedEstoqueRoute: AuthenticatedEstoqueRoute,
  AuthenticatedFundoCaixaRoute: AuthenticatedFundoCaixaRoute,
  AuthenticatedHierarquiaRoute: AuthenticatedHierarquiaRouteWithChildren,
  AuthenticatedLivesRoute: AuthenticatedLivesRouteWithChildren,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedMembrosRoute: AuthenticatedMembrosRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRouteWithChildren,
  AuthenticatedMovimentacoesRoute: AuthenticatedMovimentacoesRouteWithChildren,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRouteWithChildren,
  AuthenticatedPermissoesRoute: AuthenticatedPermissoesRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedRankingsRoute: AuthenticatedRankingsRouteWithChildren,
  AuthenticatedTicketsRoute: AuthenticatedTicketsRouteWithChildren,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedDevPageRoute: AuthenticatedDevPageRouteWithChildren,
  AuthenticatedDevBotRoute: AuthenticatedDevBotRoute,
  AuthenticatedDevConfiguracaoRoute:
    AuthenticatedDevConfiguracaoRouteWithChildren,
  AuthenticatedDevDesempenhoRoute: AuthenticatedDevDesempenhoRoute,
  AuthenticatedDevMenuLateralRoute: AuthenticatedDevMenuLateralRoute,
  AuthenticatedDevNotificacoesRoute: AuthenticatedDevNotificacoesRoute,
  AuthenticatedDevPatchNotesRoute: AuthenticatedDevPatchNotesRoute,
  AuthenticatedDevPermissoesRoute: AuthenticatedDevPermissoesRoute,
  AuthenticatedDevIndexRoute: AuthenticatedDevIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  HandleRoute: HandleRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  DevDiscordIdRoute: DevDiscordIdRoute,
  DevmlcDiscordIdRoute: DevmlcDiscordIdRoute,
  DevmlcDiscordidDiscordIdRoute: DevmlcDiscordidDiscordIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
